### ISSUE TITLE
Woocommerce REST API, nested data

### ISSUE THREAD

**Issue by DaveClissold** [cantino/huginn#1873] opened 2017-01-15 19:12 UTC
I am fairly inexperienced in the wonderful world of programming/developing and am working with Huginn for the first time. I have a question with regards to working with a web hook,  I am currently trying to setup up working with woocommerce.

I have the webhook coming to an agent ok, but there is a section of the JSON  which looks like this
```
  "meta": [
          {
            "key": "versionID",
            "label": "versionID",
            "value": "1"
          },
          {
            "key": "productCodeID",
            "label": "productCodeID",
            "value": "25"
          }
```
How can i send both the Values out with the key as the Key in the following format

KEY: VALUE

Sorry to ask what is probably a trivial question, but any help would be greatly appreciated

Kind Regards

Dave

**Comment by dsander** [comment] 2017-01-16 16:35
Hi @DaveClissold,

actually I don't think the problem is trivial because we do not have an Agent which can transform an array to a object/hash. The only solution I came up with is to use a `EventFormattingAgent` and liquid to manually construct a JSON object:

```
{
  "instructions": {
    "json": "{ {%for m in meta%}\"{{m.key}}\": \"{{m.value}}\"{% unless forloop.last %},{% endunless %}{%endfor%} }"
  },
  "mode": "clean"
}
```
You can then send that event to a `JsonParseAgent` which will parse the JSON and return a hash/object which can be used in different Agents.

**Comment by DaveClissold** [comment] 2017-01-21 17:58
Hi Dominik, 

That works a charm, but it is not escaping the '  \" '

**Comment by DaveClissold** [comment] 2017-01-22 01:03
I've just noticed an error in my original post.  the meta is nested within line_items so the json from woo reads

```
{"line_items": [
   {"name": "stochas",
     "meta": [
          {
            "key": "versionID",
            "label": "versionID",
            "value": "1"
          },
          {
            "key": "productCodeID",
            "label": "productCodeID",
            "value": "25"
          }
```

So the for loop you kindly suggested does not work if I call the full api.  Also how do i call the item name, 

`{{ line_items.name }}` 

returns blank because I'm guessing of the [, how do I ignore it?

**Comment by dsander** [comment] 2017-01-22 10:24
```
    "json": "{ {%for meta in line_items %}{%for m in meta%}\"{{m.key}}\": \"{{m.value | replace: '\"', '\\\"'}}\"{% unless forloop.last %},{% endunless %}{%endfor%}{%endfor%} }"
```
Does that work? You might need to tweak the amount of `\` to properly escape the quotes and backslashes. In the resulting event every quote should be prefixed with a backslash to escape it.

**Comment by DaveClissold** [comment] 2017-01-22 23:09
Sadly not that just thoughts out a load of backslashes

` "json": "{ \"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\",\"\": \"\" }"`

**Comment by dsander** [comment] 2017-01-23 15:06
It's probably easier to use a `JavascriptAgent`, the liquid string is hard to debug. Try this with the language set to CoffeScript:
```coffee
Agent.receive = ->
  events = @incomingEvents()
  for event in events
    data = {}
    for item in event.payload.line_items
      for meta in item.meta
        data[meta.key] = meta.value
    @createEvent data: data
```

**Comment by DaveClissold** [comment] 2017-01-23 19:07
@dsander thats it!!! thank you so much.  I do have one more question.  I have a digest working to merge the data back with the original API to now be able to send out certain bits of the data, but the liquid template is not working at all.  

Below is the output of the DIGEST AGENT
```
{
  "events": [
    {
      "data": {
        "versionID": "123",
        "productCodeID": "456"
      }
    },
    {
      "order": {
        "id": 58,
        "order_number": 58,
        "order_key": "wc_order_5886516d1d6f0",
        "created_at": "2017-01-23T18:54:37Z",
        "updated_at": "2017-01-23T18:54:37Z",
        "completed_at": "2017-01-23T18:54:37Z",
        "status": "processing",
        "currency": "GBP",
        "total": "0.00",
        "subtotal": "0.00",
        "total_line_items_quantity": 1,
        "total_tax": "0.00",
        "total_shipping": "0.00",
        "cart_tax": "0.00",
        "shipping_tax": "0.00",
        "total_discount": "0.00",
        "shipping_methods": "",
        "payment_details": {
          "method_id": "",
          "method_title": "",
          "paid": true
```

When i try and use the following in a POST agent

```
payload": {
    "VER": "{{ events.data.versionID }}",
    "EMAIL": "{{ events.order.billing_address.email }}"
  },
```

both return empty. Am I completely wrong here?

**Comment by DaveClissold** [comment] 2017-01-24 02:28
Ok was able to fix that with the following if anyone else comes across this

`"payload": {
    "VER": "{{events[0].data.versionID}}",
    "EMAIL": "{{events[1].order.billing_address.email}}"
  },`

**Comment by dsander** [comment] 2017-01-24 10:34
Awesome! We have some documentation about liquid in the [wiki](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid), the official homepage is also nice: https://shopify.github.io/liquid/

Can we close the issue?

**Comment by DaveClissold** [comment] 2017-01-24 13:18
@dsander Thanks for all your help. Sure you can close it.

**Comment by dsander** [comment] 2017-01-24 17:09
Glad I could help.

**Closed by dsander** 2017-01-24 17:09 UTC
