### ISSUE TITLE
PostAgent and XMLRPC - howto?

### ISSUE THREAD

**Issue by nata-lee** [cantino/huginn#1361] opened 2016-03-20 11:19 UTC
Hello!
Huginn makes my life easier, but some times I'm confused.

I'd like to use xml-rpc with the PostAgent. Specification here: http://xmlrpc.scripting.com/spec.html
But I can't build the sctucture with multiple parameters with the same name. Huginn doesn't let me do this, it's always a json error.
My agent:
`{
  "post_url": "http://domain/xmlrpc.php",
  "expected_receive_period_in_days": "1",
  "content_type": "xml",
  "method": "post",
  "no_merge": "true",
  "xml_root": "methodCall",
  "payload": {
    "methodName": "wp.newPost",
    "params": {
      "param": {
        "value": "1"
      }
    }
  },
  "headers": {},
  "emit_events": "false"
}`

I need more <param> and multible <member> but how? What am I doing wrong?
Could you help me?

**Comment by cantino** [comment] 2016-03-21 00:29
Hi @nata-lee, I've never actually used true XML-RPC.  (As opposed to ajax, which is usually JSON these days.)  You may want to have Huginn post to a server that logs your requests, to make sure they look right.  http://requestb.in/ could be useful here.

**Comment by nata-lee** [comment] 2016-03-25 11:59
Hi @cantino, thank you for the answer.
Well, I have no problem with XML-RPC then I use curl. And requests and responds are the next step.
I'm confused how to format XML-RPC xmls (and all xmls in general) with huginn interfase and the PostAgent. I tried to form the request as I wrote in the last message, but I can't understand how to get such structure as:

```
<methodCall>
   <methodName>examples.getStateName</methodName>
   <params>
      <param>
         <value><i4>41</i4></value>
         </param>
      <param>
         <value><user>testname</user></value>
         </param>
      </params>
   </methodCall>
```

I just need an example.

**Comment by cantino** [comment] 2016-03-26 23:40
The following JSON options are pretty close:
```json
{
  "post_url": "http://requestb.in/123456",
  "expected_receive_period_in_days": "1",
  "content_type": "xml",
  "method": "post",
  "payload": {
    "methodName": "examples.getStateName",
    "params": [
      {
        "value": {
          "i4": "41"
        }
      }
    ]
  },
  "headers": {},
  "emit_events": "false",
  "xml_root": "methodCall"
}
```

When pointing at a requestbin I made, I got this:

<img width="854" alt="screen shot 2016-03-26 at 4 39 05 pm" src="https://cloud.githubusercontent.com/assets/83835/14062972/60031b80-f371-11e5-931f-a80b88db5759.png">

**Comment by dsander** [comment] 2016-03-28 10:34
@cantino I think the problem is the `to_xml` serializer can not generate multiple `params` elements which have the same parent.

**Comment by cantino** [comment] 2016-03-29 05:00
Wait, what's the problem?  Isn't might output what @nata-lee is looking for?

**Comment by nata-lee** [comment] 2016-03-29 05:10
@dsander is quite right. I can't get multiple `param` in the `params`.
```
<params>
 <param>123</param>
 <param>456</param>
</params>
```
is impossible via huginn interface :( Or I don't know how to get it, so I asked my question.
Maybe any workaround? Now I have to use Shell Command Agent insteed of the PostAgent,and it's some kind of unsecure.

**Comment by dsander** [comment] 2016-03-29 07:28
I don't think that is possible at the moment, but I am planning to change the PostAgent to allow sending arbitrary data which can be formatted using liquid.

**Comment by dsander** [comment] 2016-04-02 09:43
@nata-lee With #1402 merged you will be able generate the XML yourself and setting it in the `payload` as a string.

**Comment by dsander** [comment] 2017-03-10 16:18
I don't think that will ever be possible with the way `to_xml` works however the workaround to to manually construct the XML structure should work.

Please feel free to reopen if you need further assistance!

**Closed by dsander** 2017-03-10 16:18 UTC
