### ISSUE TITLE
Create agent when running in docker?

### ISSUE THREAD

**Issue by mostar** [cantino/huginn#1516] opened 2016-05-23 04:59 UTC
Hi,

Beside Java Script agent, is it possible to create of modify agent when running Huginn as docker container? and if yes how to do it.

Thanks

**Comment by cantino** [comment] 2016-05-24 03:46
You mean adding a whole new Agent?  You'd need to make your own Docker build, I believe, using the Dockerfile.  We're working on making it easier by pulling agents into gems. /cc @dsander

**Comment by dsander** [comment] 2016-05-24 20:23
You could also use `docker cp` to copy the new agent into the docker container and restart it afterwards. The problem is that the copied file will be lost when you update the container to the most recent version.

**Comment by mostar** [comment] 2016-05-25 03:37
Dose updating the container is done automatic on start if there is a new version?
If yes, can I control it in the start command?
I guess If my new agent is missing I need to stop the container, docker cp and start it?

**Comment by cantino** [comment] 2016-05-25 04:46
@dsander, do you deploy your personal Huginn with Docker, or use the setup guide?  I still use Capistrano.

**Comment by dsander** [comment] 2016-05-25 08:12
@mostar No, the containers you start are always based on an image, to update it (and with that your huginn version) you need to pull the new image, remove the old container and create a new one based on the new image.
I am not sure if you can copy a file to a stopped container, but you definitely need to restart it after coping the new file in.

@cantino Yes, I switched to docker some time ago, you have to eat your own dog food, right? :)

**Comment by cantino** [comment] 2016-05-26 16:08
How do you build and maintain your personal Docker image?

**Comment by dsander** [comment] 2016-05-26 16:44
Most of the time I am running the default images, if I want to test something I build the image locally and push it to a registry. I am still working working on a [tool](https://github.com/dsander/loadmaster) which automatically builds images for the PR we get, but that does not solve the problem for custom images.
We could [move the Dockerfiles back to the project root](https://github.com/kreuzwerker/DKT.huginn/commit/ebafed9b8507142af4087b8b2fa4934303f10232) which would allow forks to build their images on Docker Hub or Quay.

**Comment by cantino** [comment] 2016-05-29 23:06
I'd have no problem moving the Docker files to the root. Any downside?

**Comment by dsander** [comment] 2016-05-30 09:03
Aside from them cluttering the root directory I don't think there are any technical downsides.

**Comment by cantino** [comment] 2016-05-30 21:40
If you'd like to move them, and think it's a good idea, I'm totally fine with it.

**Comment by cantino** [comment] 2017-01-23 18:23
I'm going to close this issue. Please reopen if you have further questions or want to make a PR.

**Closed by cantino** 2017-01-23 18:23 UTC
