### ISSUE TITLE
RSSAgent ignores multiple <category> items.

### ISSUE THREAD

**Issue by schulzpin** [cantino/huginn#955] opened 2015-08-03 22:37 UTC
RSSAgent ignores category items except the first one.
 
For example each article in this feed has multiple categories but Huginn sees only one. 
http://feeds.mashable.com/Mashable

Is there a way to parse them all?

**Comment by cantino** [comment] 2015-08-04 05:06
This is likely a deficiency of with the underlying RSS parsing gem that we use.  We ask for `categories` when we use it.  It may be necessary for us to upgrade the Gem or find / write a new one.

**Comment by knu** [comment] 2015-08-04 10:35
RSS::Parser parses categories correctly, but FeedNormalizer somehow [only takes the first one](https://github.com/aasmith/feed-normalizer/blob/master/lib/parsers/rss.rb#L94-L96) in the default (non-loose) mode.

**Comment by Jngai** [comment] 2016-02-17 21:18
I am aware that @knu is still working on it. I have looked into his work/commits in the reference pr. I am just having trouble reproducing this error. I tried two examples mashable and wired feeds.

```
{
  "id": "http://www.wired.com/?p=1976016",
  "date_published": "2016-02-17 20:54:53 +0000",
  "last_updated": "Wed, 17 Feb 2016 20:54:53 +0000",
  "url": "http://www.wired.com/2016/02/new-5-million-x-prize-for-ai-that-gives-the-best-ted-talk/",
  "urls": [
    "http://www.wired.com/2016/02/new-5-million-x-prize-for-ai-that-gives-the-best-ted-talk/"
  ],
  "description": "<div class=\"rss_thumbnail\"><img src=\"http://www.wired.com/wp-content/uploads/2016/02/TED2016_021716_3BH0087-660x440.jpg\" alt=\"New $5 Million X Prize for AI That Gives the Best TED Talk\" /><\/div><p>The prize will give a whole new meaning to the term \"TED talk.\"<\/p>\n<p>The post <a rel=\"nofollow\" href=\"http://www.wired.com/2016/02/new-5-million-x-prize-for-ai-that-gives-the-best-ted-talk/\">New $5 Million X Prize for AI That Gives the Best TED Talk<\/a> appeared first on <a rel=\"nofollow\" href=\"http://www.wired.com\">WIRED<\/a>.<\/p>\n",
  "content": "<div class=\"rss_thumbnail\"><img src=\"http://www.wired.com/wp-content/uploads/2016/02/TED2016_021716_3BH0087-660x440.jpg\" alt=\"New $5 Million X Prize for AI That Gives the Best TED Talk\" /><\/div><p>The prize will give a whole new meaning to the term \"TED talk.\"<\/p>\n<p>The post <a rel=\"nofollow\" href=\"http://www.wired.com/2016/02/new-5-million-x-prize-for-ai-that-gives-the-best-ted-talk/\">New $5 Million X Prize for AI That Gives the Best TED Talk<\/a> appeared first on <a rel=\"nofollow\" href=\"http://www.wired.com\">WIRED<\/a>.<\/p>\n",
  "title": "New $5 Million X Prize for AI That Gives the Best TED Talk",
  "authors": [
    "Issie Lapowsky"
  ],
  "categories": [
    "Business",
    "Artificial Intelligence",
    "TED",
    "TED 2016",
    "XPRIZE"
  ]
}
```

{
  "id": "http://mashable.com/?p=4324379",
  "date_published": "2016-02-17 20:42:14 +0000",
  "last_updated": "Wed, 17 Feb 2016 20:42:14 +0000",
  "url": "http://feeds.mashable.com/~r/Mashable/~3/V-990WXQn70/",
  "urls": [
    "http://feeds.mashable.com/~r/Mashable/~3/V-990WXQn70/"
  ],
  "description": "<img alt=\"Bob-ross-revenant\" src=\"http://rack.1.mshcdn.com/media/ZgkyMDE2LzAyLzE3LzdkL2JvYnJvc3NyZXZlLmI0OGVhLmpwZwpwCXRodW1iCTU3NXgzMjMjCmUJanBn/9145d251/22e/bob-ross-revenant.jpg\" /><div style=\"float: right; width: 50px;\"><a href=\"http://twitter.com/share?via=Mashable&text=If+Bob+Ross+painted+%E2%80%98The+Revenant%E2%80%99+and+all+its+happy+little+bears&src=http%3A%2F%2Fmashable.com%2F2016%2F02%2F17%2Fbob-ross-revenant%2F\" <script>zAyLzE3LzE1L0Jyb2FkQ2l0eUNvLmEzMjAzLmpwZwpwCXRodW1iCTk1MHg1MzQjCmUJanBn/72e0d856/e74/BroadCityColbert_Thumbnail.jpg\" data-z=\"560x316#\"><\/span><\/span><\/a><a class=\"title\" href=\"http://mashable.com/2016/02/17/broad-city-stephen-colbert/\" data-crackerjax=\"#post-slider\">'Broad City' stars teach Stephen Colbert that rainbow bagels are the key to being cool<\/a><\/p><\/div>\n<div><p><a ;utm_medium=rss&amp;utm_source=\"><a href=\"http://mashable.com/watercooler/?utm_campaign=Mash-Prod-RSS-Feedburner-All-Partial&amp;utm_cid=Mash-Prod-RSS-Feedburner-All-Partial\">Watercooler<\/a>, and <a href=\"http://mashable.com/category/viral-video-template/?utm_campaign=Mash-Prod-RSS-Feedburner-All-Partial&amp;utm_cid=Mash-Prod-RSS-Feedburner-All-Partial\">Viral Video Template<\/a><img src=\"http://feeds.feedburner.com/~r/Mashable/~4/V-990WXQn70\" height=\"1\" width=\"1\" alt=\"\"/>",
  "title": "If Bob Ross painted &#8216;The Revenant&#8217; and all its happy little bears",
  "authors": [
    "Jonathan Keshishoglou"
  ],
  "categories": [
    "Videos",
    "Viral Video",
    "Bob Ross",
    "Watercooler",
    "Viral Video Template"
  ]
}

What is a failing scenario for this as in categories not getting captured? Seems like it is getting captured....

**Comment by cantino** [comment] 2016-02-20 21:06
Thanks for looking into it @Jngai! @schulzpin, do you still have this issue?

**Comment by Jngai** [comment] 2016-04-04 19:08
@cantino maybe you should close it. I think it will make the issues cleaner.

**Comment by cantino** [comment] 2016-04-09 03:16
Agreed, since we didn't hear back.

**Closed by cantino** 2016-04-09 03:16 UTC
Labels: bug, enhancement, help-wanted
