### ISSUE TITLE
How to resolve the  exception in Adioso Agent?

### ISSUE THREAD

**Issue by rselvi** [cantino/huginn#645] opened 2014-11-13 10:47 UTC
I have created a Adioso agent.I have defined username and password.While running it throws following exception in the log tab
     Exception during check:  undefined method `gsub' for nil:NilClass

**Comment by Ishfal** [comment] 2015-08-08 20:10
Just wanted to add a +1 on this... I've reconfirmed log-in information is correct but I get the same result as rselvi above. Also, I attempted to find any information on the Adioso API on their website to no avail, and when trying to directly HTTP GET the Adioso API, my correct log-in info is rejected. Is the AdiosoAgent working for others? Does their API work for others?

**Comment by Ishfal** [comment] 2015-09-05 02:16
Circling back on this... I've reached out to Adioso to see if the API is still open / available. Doing a little more tracing makes me doubly suspicious that the AdiosoAgent itself is working fine and that the end-point (Adioso) is the issue.

**Comment by cantino** [comment] 2015-09-05 17:03
Thanks for digging in @Ishfal.  I don't use Adioso, so have no way to test it.

**Comment by rubella** [comment] 2015-10-18 07:55
I'm getting the same error with the Adioso Agent. Login credentials are confirmed and I've tested the search on the Adioso website without issue.

'undefined method `gsub' for nil:NilClass'

**Comment by cantino** [comment] 2015-10-21 05:58
It seems like they've turned off their API.  See also https://github.com/cantino/huginn/issues/1088

**Comment by dsander** [comment] 2017-03-10 16:27
Closing since we removed the Agent 😄

**Closed by dsander** 2017-03-10 16:27 UTC
Labels: issue
