### ISSUE TITLE
How to remove images from rss-feeds

### ISSUE THREAD

**Issue by lienas** [cantino/huginn#1046] opened 2015-09-29 09:14 UTC
in some descriptions of rss feeds images are included 
example: `"description": "<img src=\"http://www.it-times.de/resources/dam/asset/5371/ittimes_news_detail.jpg\" /><br /> SUNNYVALE (IT-Times) - Das ...`.
How can I remove the complete image tag ?

**Comment by level20peon** [comment] 2015-09-30 06:02
Pass those feeds through an EventFormattingAgent:

    {
      "instructions": {
        "description": "{{ description | regex_replace: '<img.*?>', '' }}"
      },
      "mode": "clean"
    }

**Comment by alvarodemig** [comment] 2015-09-30 14:22
Hi, i tried this but didn't work... any idea? Thanks!!!!

{
  "instructions": {
    "url": "{{ url | regex_replace: 'oldtext', 'newtext' }}"
  },
  "mode": "clean"
}

**Comment by level20peon** [comment] 2015-09-30 14:26
could you attach the diagram of your agent event flow?

**Comment by level20peon** [comment] 2015-09-30 14:28
And maybe add `(?m)` to that regex in case those tags spread accross multiple lines (i.e. `regex_replace: '(?m)<img.*?>'` ...)

**Comment by alvarodemig** [comment] 2015-09-30 14:29
![image](https://cloud.githubusercontent.com/assets/14134694/10195883/8c2f35ca-6755-11e5-8f04-6ce1a8ba527b.png)

Intermediate (2) is just to make some probes.

website agent --> EventFormattingAgent --> Data output agent

**Comment by level20peon** [comment] 2015-09-30 14:33
What's the name of the `extract` object in your WebsiteAgent? If it's not url, you have to adjust this in the EventFormattingAgent. In this case it's named `content`:

    {
      "expected_update_period_in_days": "14",
      "url": "http://www.example.com",
      "type": "html",
      "mode": "on_change",
      "extract": {
        "content": {
          "css": "div#main div.listing ul li:not(:nth-child(1))",
          "value": "./node()"
        }
      }
    }

**Comment by alvarodemig** [comment] 2015-09-30 14:41
If you don´t mind i write here all the steps. Im not a computer science guy and it's complicated for me... 

What i need to do is to get a RSS, change some information of the url an create another RSS.
That change is what i can not do...


WEBSITE AGENT

{
  "expected_update_period_in_days": "2",
  "url": "http://thersslinkimworkingon.rss",
  "type": "xml",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "//link",
      "text": "true"
    },
    "title": {
      "xpath": "//title",
      "text": "true"
    },
    "description": {
      "xpath": "//description",
      "text": "true"
    }
  }
}

EVENT FORMATTING

{
"instructions": {
"url": "{{ url | regex_replace: 'oldtext', 'newtext' }}"
},
"mode": "clean"
}


DATA OUTPUT

{
  "secrets": [
    "secret"
  ],
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "90minspain",
    "description": "Noticias fútbol España",
    "item": {
      "title": "{{title}}",
      "description": "{{description}}",
      "link": "{{ url }} ",
      "pubDate": "{{pubDate}}"
    }
  }
}

**Comment by level20peon** [comment] 2015-09-30 14:45
Looks ok, but I cannot help you any further if you don't provide the link to your feed and the exact regex you're using.

**Comment by alvarodemig** [comment] 2015-09-30 14:51
ok, here you have all the information. Maybe is that isnt working the regex_resplace in huginn??


{
  "expected_update_period_in_days": "2",
  "url": "http://www.90min.com/es/leagues/la-liga.rss",
  "type": "xml",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "//link",
      "text": "true"
    },
    "title": {
      "xpath": "//title",
      "text": "true"
    },
    "description": {
      "xpath": "//description",
      "text": "true"
    }
  }
}

-------------------------------------------------------
{
  "instructions": {
    "url": "{{ url | regex_replace 'utm_source=RSS', 'a_aid=35187'}}"
  },
  "matchers": [

  ],
  "mode": "clean",
  "skip_agent": "true",
  "skip_created_at": "true"
}

**Comment by level20peon** [comment] 2015-09-30 15:13
There are multiple problems in the website agent, preventing it from grabbing the data in the first place. So The EventFormattingAgent doesn't have anything to parse.
Use this as the WebSiteAgent:

    {
      "expected_update_period_in_days": "2",
      "url": "http://www.90min.com/es/leagues/la-liga.rss",
      "type": "xml",
      "mode": "on_change",
      "extract": {
        "link": {
          "xpath": "/rss/channel/item/link",
          "text": "true"
        },
        "title": {
          "xpath": "/rss/channel/item/title",
          "text": "true"
        },
        "description": {
          "xpath": "/rss/channel/item/description",
          "text": "true"
        }
      }
    }

Then use this as EventFormattingAgent:

    {
      "instructions": {
        "url": "{{ link | regex_replace 'utm_source=RSS', 'a_aid=35187'}}"
      },
      "matchers": [],
      "mode": "clean",
      "skip_agent": "true",
      "skip_created_at": "true"
    }

I didn't test the second agent, but it should work.

**Comment by alvarodemig** [comment] 2015-09-30 15:24
Thanks! im gonna try and i tell you if it works ;)

**Comment by alvarodemig** [comment] 2015-09-30 19:39
It doesn't work :(

This is the result:
 "url": "http://90min.com/es/posts/2604253-cristiano-marca-el-gol-numero-500-de-su-carrera-e-iguala-un-record-historico-de-raul?utm_source=RSS"

Do u know another different way to manage this issue?

**Comment by HyShai** [comment] 2015-09-30 20:51
@alvarodemig you're missing a colon after `regex_replace`.
```
"url": "{{ link | regex_replace: 'utm_source=RSS', 'a_aid=35187'}}"
```

**Comment by alvarodemig** [comment] 2015-09-30 21:30
Thanks @HyShai , i've tried but still not working... i don't know what is the problem

**Comment by HyShai** [comment] 2015-09-30 21:35
Can you post again all the relevant agents as they are currently?

**Comment by alvarodemig** [comment] 2015-09-30 21:40
Yes sure, thank you very much for your time @HyShai 

WEBSITE AGENT

{
  "expected_update_period_in_days": "2",
  "url": "http://www.90min.com/es/leagues/la-liga.rss",
  "type": "xml",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "/rss/channel/item/link",
      "text": "true"
    },
    "title": {
      "xpath": "/rss/channel/item/title",
      "text": "true"
    },
    "description": {
      "xpath": "/rss/channel/item/description",
      "text": "true"
    }
  }
}

EVENT FORMATTING AGENT

{
  "instructions": {
    "url": "{{ url | regex_replace: 'utm_source=RSS', 'a_aid=35187'}}"
  },
  "matchers": [

  ],
  "mode": "merge",
  "skip_agent": "true",
  "skip_created_at": "true"
}

---------------------------------------------------------------
AND THE RESULT...

{
  "url": "http://90min.com/es/posts/2602301-ibrahimovic-ataca-a-cr7-en-el-united-rooney-hacia-todo-el-trabajo-y-cristiano?utm_source=RSS",

And continues, but it should be:

 "url": "http://90min.com/es/posts/2602301-ibrahimovic-ataca-a-cr7-en-el-united-rooney-hacia-todo-el-trabajo-y-cristiano?a_aid=35187",

**Comment by HyShai** [comment] 2015-09-30 21:46
Try removing 
```
"skip_agent": "true",
"skip_created_at": "true"
```

**Comment by alvarodemig** [comment] 2015-09-30 21:49
It's not possible...

1 error prohibited this Agent from being saved:
instructions, mode, skip_agent, and skip_created_at all need to be present.

**Comment by HyShai** [comment] 2015-09-30 21:53
Oh wow you're using a really old version - when have you updated last?

**Comment by alvarodemig** [comment] 2015-09-30 22:58
I'm using Huginn through terminal.com, it was really easy to deploy there. Do you know if i can update it?

**Comment by cantino** [comment] 2015-10-01 03:37
Unfortunately I don't know anything about terminal.com.  Have you asked them about updating?

**Comment by HyShai** [comment] 2015-10-01 03:39
Wasn't the huginn deployment to terminal.com the precursor to deployment on Heroku?

**Comment by alvarodemig** [comment] 2015-10-01 03:51
i will definitely ask them. I'm gonna do it now.

You can run huginn in less than 5 minutes with them, what is really conveniant for people like me who hasn't the technical background. It's a pity they work with an old version. I had some issues trying to deploy on Heroku...

I will say you something when i get any response!

And again thank u very much, i really appreciate what you do

**Comment by alvarodemig** [comment] 2015-10-03 17:25
Great!
Terminal.com updated Huginn and now it works!!! :D 

Now i just have one question... i created a new RSS with the DataOutputAgent, the problem is that isn't public and i wanna do some actions with IFTTT with that created RSS.
How could i do that?

**Comment by cantino** [comment] 2015-10-03 20:05
Does your Huginn instance on terminal.com have a URL that you can visit when not logged into terminal.com?  That would be the base of the path to your data output agent.

**Comment by alvarodemig** [comment] 2015-10-06 13:35
Perfect and fixed! i could open a port.

**Comment by cantino** [comment] 2015-10-08 04:12
Sounds like it's fixed!  Okay if we close this Issue?

**Comment by lienas** [comment] 2015-10-08 10:09
Yes, for me ist ok

**Comment by cantino** [comment] 2015-10-08 16:29
Great!

**Closed by cantino** 2015-10-08 16:29 UTC
