### ISSUE TITLE
Email agent stripping out tags?

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#1373] opened 2016-03-26 17:08 UTC
I've updated my huginn instance to the latest version and I'm noticing that the email agent is stripping out a number of tags like table.

Here is a test page: http://rockandsock.neocities.org/index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>The web site of rockandsock</title>
    <!-- The style.css file allows you to change the look of your web pages.
         If you include the next line in all your web pages, they will all share the same look.
         This makes it easier to make new pages for your site. -->
    <link href="/style.css" rel="stylesheet" type="text/css" media="all">
  </head>
  <body>
    <h2>Email Template</h2>
    <table width="600" cellpadding="0" cellspacing="0" align="center">
        <tr>
            <td width="200">
                <h2>Side bar</h2>
                <p>Test</p>
            </td>
            <td width="400">
                <h2>Main Content</h2>
                <p>Some stuff here</p>
                <table width="100%">
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </table>
  </body>
</html>
```

This is a test scenario demonstrating the issue:

```json
{
  "schema_version": 1,
  "name": "Test HTML email",
  "description": "No description provided",
  "source_url": false,
  "guid": "4e458982c373314efea506e8f2085f39",
  "tag_fg_color": "#ffffff",
  "tag_bg_color": "#5bc0de",
  "exported_at": "2016-03-26T16:59:00Z",
  "agents": [
    {
      "type": "Agents::EmailAgent",
      "name": "A_Test - Email",
      "disabled": false,
      "guid": "9f39fc6ac572bfc0473ebae1732403ee",
      "options": {
        "subject": "You have a notification!",
        "expected_receive_period_in_days": "2",
        "body": "{{body}}",
        "content_type": "text/html"
      },
      "propagate_immediately": true
    },
    {
      "type": "Agents::WebsiteAgent",
      "name": "A_Test - in",
      "disabled": false,
      "guid": "4d2ad8ecda6496a3d70af665543f0d1b",
      "options": {
        "expected_update_period_in_days": "2",
        "url": "http://rockandsock.neocities.org/",
        "type": "html",
        "mode": "on_change",
        "extract": {
          "body": {
            "css": "body",
            "value": "."
          }
        }
      },
      "schedule": "every_12h",
      "keep_events_for": 3600,
      "propagate_immediately": false
    }
  ],
  "links": [
    {
      "source": 1,
      "receiver": 0
    }
  ],
  "control_links": [

  ]
}
```

The older instance sends emails as expected (with tables)...
Any ideas what the issue could be?

**Comment by dsander** [comment] 2016-03-26 17:49
Hi @irfancharania,

I can confirm the tables are tripped from the HTML but can not remember a change that could have caused it. Do you know which in revision of Huginn it worked?

**Comment by irfancharania** [comment] 2016-03-26 18:01
What's the easiest way for me to tell what revision an instance is?
The latest entry in changes.md in the working instance is from Oct 17, 2015

**Comment by dsander** [comment] 2016-03-26 18:42
`git log | head -n1` should give you the sha of the latest commit of your instance.

**Comment by irfancharania** [comment] 2016-03-26 18:45
commit efb3bc413613910b69d1381c6f54214ef7168206

**Comment by dsander** [comment] 2016-03-26 21:45
I did some bisecting and found that 05a4c32ac4dc757096a45c5ea4e3ae369da63418 changed the behavior. However the rails CHANGELOGs did not seem to mention anything: https://github.com/rails/rails/compare/v4.2.4...v4.2.5.1
The issue might be the upgrade of `rails-html-sanitizer` https://github.com/rails/rails-html-sanitizer/compare/v1.0.2...v1.0.3 specifically this commit https://github.com/rails/rails-html-sanitizer/commit/297161e29a3e11186ce4c02bf7defc088bf544d4, even if it was a bugfix that's pretty big change for a patch release. Probably nobody noticed that it would also affect HTML emails.

I think we need to figure out how the HTML sanitizer was configured before the rails 4.2.5.1 upgrade and override the defaults in our configuration.

/cc @cantino @knu

**Comment by irfancharania** [comment] 2016-03-26 22:20
I'd guess it's due to the restrictive set of allowable tags/attributes (here)[https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails/html/sanitizer.rb#L107-L110]?

Would it be possible to define a more permissive global whitelist in Huginn?

**Comment by cantino** [comment] 2016-03-26 23:20
Based on [this article](http://blog.plataformatec.com.br/2014/07/the-new-html-sanitizer-in-rails-4-2/), it looks like you could set `Rails::Html::Sanitizer.allowed_tags = Rails::Html::Sanitizer.allowed_tags + Set.new %w(table)` in a new initializer in `config/initializers` and see if it fixes it for you?

**Comment by irfancharania** [comment] 2016-03-27 00:06
Can you tell me what I'm doing wrong here?

```bash
sudo -u huginn -H nano sanitizer.rb
```

paste in ```Rails::Html::Sanitizer.allowed_tags = Rails::Html::Sanitizer.allowed_tags + Set.new %w(table)```

``` bash
sudo bundle exec rake production:restart
service nginx restart

sudo bundle exec rake production:check
(in /home/huginn/huginn)
[  OK  ] Everything is fine
```

That gives me a 502 error, and 'huginn_error.log' just has connection refused entries

**Comment by cantino** [comment] 2016-03-27 03:07
Actually, try `ActionView::Base.sanitized_allowed_tags += Set.new(%w[table])` instead.

**Comment by irfancharania** [comment] 2016-03-27 03:56
That's better!

Silly question, but how do I add more tags?
I've tried ``%w[table, thead, tbody, tr, th, td]`` and ``%w(table, thead, tbody, tr, th, td)`` but they both only take the last listed tag

**Comment by cantino** [comment] 2016-03-27 03:58
Without the commas.  `%w(table thead)` is Ruby shorthand for `['table', 'thead']`

**Comment by irfancharania** [comment] 2016-03-27 03:59
Also, for future, how would I hunt down the source of that 502 error I was getting before?

**Comment by cantino** [comment] 2016-03-27 04:02
I'd expect to see it in the production.log in log/ in the app directory.

**Comment by irfancharania** [comment] 2016-03-27 04:10
Your solution works!

So you think we can add it in the main branch?

Here's what I've got: sanitizer.rb
```ruby
ActionView::Base.sanitized_allowed_tags += Set.new(%w(table thead tbody tr td))
ActionView::Base.sanitized_allowed_attributes += Set.new(%w(border cellspacing cellpadding))
```

**Comment by cantino** [comment] 2016-03-27 05:32
Seems safe to me.  Want to send a PR?

**Comment by irfancharania** [comment] 2016-03-27 17:35
Sent pull request #1380

**Comment by cantino** [comment] 2016-03-27 21:37
Merged, thanks for the fix!

**Closed by cantino** 2016-03-27 21:37 UTC
