### ISSUE TITLE
Trigger Agent Filtering now working properly

### ISSUE THREAD

**Issue by xdirty** [cantino/huginn#1469] opened 2016-05-02 23:23 UTC
I created a trigger agent to filter event from another trigger agent. basically i want to filter anything that slips through the cracks from the previous trigger agent but since im using must "match one" i have to do a separate trigger agent. so i have multiple trigger agents for different feeds with "regex" filtering what i want to keep from the events, then it passes through the results i want, then i want to filter the results for a couple undesirable results that slip though, so i use "!regex" to filter those unwanted keywords and let the rest of the events pass through.

I tried to check everything, but it does not filter any of the events, everything just goes right through without it filtering anything

Heres what i got

```
{
  "expected_receive_period_in_days": "14",
  "keep_event": "true",
  "must_match": "1",
  "rules": [
    {
      "type": "!regex",
      "value": "Keyword1|keyword2",
      "path": "title"
    },
    {
      "type": "!regex",
      "value": "Keyword1|keyword2",
      "path": "description"
    },
    {
      "type": "!regex",
      "value": "Keyword1|keyword2",
      "path": "url"
    }
  ]
}
```

**Comment by cantino** [comment] 2016-05-04 03:53
I think this is going through because !regex matches if the test DOESN'T have something, so if any event doesn't match Keyword1|keyword2 in the title, it goes through, irregardless of the other two matchers.  Make sense?

**Comment by xdirty** [comment] 2016-05-04 20:49
First off, i wanted to thank you for taking the time to help me. I think I understand what you are saying  but how do i remedy the situation?  3 differ trigger agents?  Or remove must match one?

**Comment by cantino** [comment] 2016-05-16 03:18
The problem is, I assume, that almost everything matches `title != keyword1 OR description != keyword1 OR url != keyword1`, so just about everything gets through.  I don't fully understand what you're trying to do, though.

**Comment by cantino** [comment] 2017-01-23 18:25
I'm going to close this issue. Please reopen if you have further questions.

**Closed by cantino** 2017-01-23 18:25 UTC
