### ISSUE TITLE
PostAgent merge and re-emit

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1801] opened 2016-11-18 02:05 UTC
I have a agent flow where event is sent to PostAgent, which uses part of the payload to post. Then the result of the PostAgent has to merge with the original event and go to the next agent. 

no_merge is set to false and emit_events is set to true but events are not merging.

How can I achieve this?

**Comment by dsander** [comment] 2016-11-18 15:08
This is a duplicate of #1723, please check for existing issues before opening a new one.

**Closed by dsander** 2016-11-18 15:08 UTC
