### ISSUE TITLE
UI problems with an installation on Ubuntu

### ISSUE THREAD

**Issue by Mike77S** [cantino/huginn#970] opened 2015-08-13 17:07 UTC
Hi, first I would like to thank everybody in the comunity for the work that have been done with huginn it's really an amazing tool !
I'm a novice an I try to deploy huginn (as a replacement of Yahoo Pipes) on my Ubuntu's Server. I've follow the instructions provided here:

 https://github.com/dsander/huginn/blob/deployment-guide/doc/manual/installation.md

Everything works fine excepted the UI that looks terrible (take a look at the screenschot)
![huginn](https://cloud.githubusercontent.com/assets/8396905/9256145/28de52d0-41ee-11e5-989b-4c5d4080469e.png)

Can someone help me ? 
Thanks a lot ;)

P.S here's my config:
Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)
1.75 GB of RAM
1 Core

**Comment by virtadpt** [comment] 2015-08-13 18:24
Do you have a web server like Nginx or Apache sitting in front of it?  It looks like it's not configured to proxy static assets (i.e., CSS).

**Comment by Mike77S** [comment] 2015-08-13 19:21
Thanks a lot for your reply !
Yes, I use Nginx just as describe in documentation. 
"It looks like it's not configured to proxy static assets (i.e., CSS)."
Can you explain me briefly how can I do that ? I did not really find answers on the web,...

**Comment by virtadpt** [comment] 2015-08-13 20:15
The process for going about it isn't terribly well documented; it's referenced in the deployment guide you linked to but it involves dropping a pre-built Nginx configuration file from the Huginn source code that is a little problematic.  Here's the bit I needed to make it work at the server{} level of the site-specific config file:
```
root /home/drwho/huginn/public;
try_files $uri/index.html $uri.html $uri @app;
```

**Comment by cantino** [comment] 2015-08-14 05:49
Welcome @Mike77S!  Perhaps you haven't compiled static assets at all?

Did you run the step that looks like this?

```
sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production
```

**Comment by Mike77S** [comment] 2015-08-14 07:12
@cantino Thanks for the reply, Yes I've done that

**Comment by cantino** [comment] 2015-08-15 03:13
@dsander, do you have any ideas?

**Comment by dsander** [comment] 2015-08-15 09:04
Hi @Mike77S 

is it possible you changed the permission of the `/home/huginn` directory? It needs to be set to `755` so nginx can access the public files in `/home/huginn/huginn/public/`.

If that does not help can you paste the last few lines of `/var/log/nginx/huginn_error.log`?

**Comment by virtadpt** [comment] 2015-08-22 23:19
Hi, @Mike77S - are you still having problems with static assets?

**Comment by TheGuismo** [comment] 2015-08-26 14:09
Hi everybody,

I have exactly the same problem as @Mike77S.

I try your thing @virtadpt, but I have to say that I'm a total newbie on linux distribution and the command juste give me error (`try_files$uri is not defined in current scope`).

I have correctly compile the static assets.

@dsander, I check the permission of the `/home/huginn` directory and it's correctly 755. Just to be sure I have do this command `sudo chmod -R 755 huginn` on the user huginn's directory.

The log file `/var/log/nginx/huginn_error.log` is completly empty.

So I check the other log. `/home/huginn/log/unicorn.log` have no error but `/home/huginn/huginn/log/production.log` have few error like that :

`FATAL -- : [...] ActionController::RoutingError (No route matches [GET] "/assets/spinner-arrows-[...].gif"): config/initializers/silence_worker_status_logger.rb:5:in 'call_with_silence_worker_status'`

Hope that can help you to tell us what is wrong with our configuration.

**Comment by dsander** [comment] 2015-08-26 18:49
@TheGuismo It looks like nginx is not configured properly, did you use the [example configuration](https://github.com/cantino/huginn/blob/master/deployment/nginx/huginn) from the guide? The only thing you need to change is the `server_name`

**Comment by TheGuismo** [comment] 2015-08-27 09:25
@dsander Just to be sure I have redo the step associate with the nginx configuration and I change the line `server_name YOUR_SERVER_FQDN; ` to `server_name huginn.phoenix-isi.fr; ` phoenix-isi.fr is our domain name.

When I start the server this morning at my first connexion at Huginn UI, I have error on `huginn_error.log` but this error never appear after (and I do a lot of test) : 

`2015/08/27 10:15:30 [crit] 3557#0 : *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (13: Permission denied) while connecting to upstream, client: 10.5.5.50, server: huginn.phoenix-isi.fr, request: "GET / HTTP/1.0", upstream: "http://unix://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/"`

And the same message for `unicorn.socket:/502.html` I have recheck the permission of these directory and all have `huginn` as owner and 755 in permission. The weirdest is that I can't reiterate this error.

And I still have the error message with the `ActionController::RoutingError`.

**Comment by dsander** [comment] 2015-08-27 16:07
@TheGuismo does the `root_path` ( /home/huginn/huginn/public) that is set in the nginx config file exist?

**Comment by TheGuismo** [comment] 2015-08-27 16:22
@dsander Yes, the `root_path` exist.

**Comment by dsander** [comment] 2015-08-27 18:56
@TheGuismo Are the permissions of the `public` directory set correctly? It needs to be accessible by the `www-data` user. You should also have a bunch of files in that directory. If that is not the case you need to run `sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production`

**Comment by TheGuismo** [comment] 2015-08-28 08:37
@dsander The permission of the `public` directory are : `drwxrr-xr-x` with `huginn` as owner. In that directory I have bunch of files like `apple-touch-icon-144x144.png` and a directory `assets` with inside a bunch of files like `spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif` (exactly the same name in the error message).

**Comment by dsander** [comment] 2015-08-28 10:20
@TheGuismo That is really odd, can you restart nginx and huginn and post the log entries of the files listed in the [troubleshooting](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting) section again?

**Comment by TheGuismo** [comment] 2015-09-02 14:13
@dsander Sorry for the wait. I reinstall completly my virtual machine to be sure that I haven't skip a step or anything else.
I may have target where the error could come. I have some issues with the [Procfile](https://github.com/cantino/huginn/blob/master/Procfile).
If I don't change it, I have the problem that we discuss here which nginx can't rout to the static assets. But it's for development.
So I comment out the new threaded worker for development (ligne 6 and 7) and I uncomment the threaded worker in the production's part (ligne 24 and 25).

I export the config with `sudo rake production:export` and restart nginx `sudo service nginx restart`

I try a `sudo rake production:status` : 
`run: huginn-jobs-1: (pid 4165) 33s; run: log: (pid 4178) 32s
run: huginn-web-1: (pid 4168) 33s; run: log: (pid 4177) 32s`

And with a `sudo rake prodction:check` : 
`[    OK    ] Everything is fine`

But when I go to `http://localhost:3000/`, I have an `Unable to connect` error.

So i check the log files : 
 * `/var/log/nginx/huginn_error.log` is completly empty like always
 * `/home/huginn/huginn/log/unicorn.log` has some entries :       
`I, [2015-09-02T15:48:41.590901 #4168] INFO -- : Refreshing Gem list       
I, [2015-09-02T15:48:49.052510 #4168] INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket         
I, [2015-09-02T15:48:49.052944 #4168] INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=8         
I, [2015-09-02T15:48:49.089783 #4168] INFO -- : master process ready        
I, [2015-09-02T15:48:49.111427 #4219] INFO -- : worker=0 ready       
I, [2015-09-02T15:48:49.120160 #4222] INFO -- : worker=1 ready`
* `/home/huginn/huginn/log/production.log` :  
![production](https://cloud.githubusercontent.com/assets/13982340/9633325/94352be6-518c-11e5-9004-f25087caf1d6.jpg)
Until the end of the file

* `/home/huginn/huginn/log/jobs-1/current` nothing wrong just some `Queuing schedule for [every_1m/every10m/every_2m/every_5m/7am]` and `Queuing event propagation`

Hope that can help you to tell me what is wrong.

**Comment by cantino** [comment] 2015-09-02 14:56
@TheGuismo, it looks like it's running correctly.  Do you have `-b0.0.0.0` in your copy of the Procfile?  Is this running in a virtual machine, or on you main computer.  If it's in a virtual machine, do you have port forwarding configured so that your main computer could see the virtual machine on port 3000?

**Comment by dsander** [comment] 2015-09-02 15:01
@TheGuismo Yes that looks correct, however `http://localhost:3000/` is used in development. When you installed the nginx config file and restarted nginx you should be able to access huginn via the IP or FQDN of your VM `http://<ip>`

**Comment by TheGuismo** [comment] 2015-09-02 15:10
@dsander @cantino  oh damn that was so easy ! I was to focus on port 3000. Now that I go `http://<ip>` it's worked perfectly ! It's always the easier thing that I can't do. Really thanks for your help. Now I can play with it.

**Comment by cantino** [comment] 2015-09-02 15:11
Very glad it's working!

Please close the issue if everything is fixed.

**Comment by TheGuismo** [comment] 2015-09-02 15:15
Well I'm not the one who open it, I think it's at @Mike77S to do it.

**Comment by Guygox** [comment] 2015-11-30 10:39
Sorry for diging up this thread. I have some kind of common problem :+1: While using port 3000 I have no pics (login works, the page appears). And while using the classic tcp port I have a "502 error". I really don't know how to do. I checked my conf and I don't see where the problem is...

Thnaks for all !

**Comment by dsander** [comment] 2015-11-30 11:24
Hi @Guygox,

did you follow the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md)? If you did, I think you diverged at some point, because per default huginn should not listen on port 3000.

To fix the missing images you probably need to run `sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production`

**Comment by Guygox** [comment] 2015-11-30 14:45
I followed the guide. Images are in the right folder. I tried to enter the command you wrote (I already did it while following the guide), but still no success.

![huggin](https://cloud.githubusercontent.com/assets/16080644/11474469/8463bb06-9778-11e5-947e-3bc32f7d720e.png)
![huggin2](https://cloud.githubusercontent.com/assets/16080644/11474598/5970373e-9779-11e5-891b-b8ae627ee971.png)

**Comment by dsander** [comment] 2015-11-30 16:39
Is there anything suspicious in the log files listed [in the troubleshooting section](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting)? Especially `/var/log/nginx/huginn_error.log` would be interesting.

**Comment by Guygox** [comment] 2015-11-30 16:51
jp@Huginn:/home/huginn/huginn$ sudo rake production:check
[  OK  ] Everything is fine

While checking the Unicorn log /home/huginn/huginn/log/unicorn.log
2015/11/30 17:45:14 [crit] 55844#0: *4 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 192.168.145.41, server: huginn, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "huginn"

I can access the folder but it's empty...

And the Production Log is empty

**Comment by dsander** [comment] 2015-11-30 17:10
That output more looks like from the nginx error log

When `/home/huginn/huginn/tmp/sockets/unicorn.socket` does not exist huginn is probably not running `sudo rake production:restart` will (re)start it.

Does `sudo -u www-data ls -al /home/huginn/huginn/public/assets/` list the files in the directory?

**Comment by Guygox** [comment] 2015-12-01 13:32
I restart it.
And yes the sudo ls for www-data list all the files : jp@Huginn:/home/huginn/huginn$  sudo -u www-data ls -al /home/huginn/huginn/public/assets
total 1356
drwxr-xr-x 4 huginn huginn   4096 nov.  30 15:35 .
drwxr-xr-x 3 huginn huginn   4096 nov.  27 11:05 ..
-rwxr-xr-x 1 huginn huginn 423363 nov.  27 10:53 ace-7379624ab80c5810912931db3d77f8c315a6656df9f9e9713c69cf13b08f29ee.js
-rwxr-xr-x 1 huginn huginn 298594 nov.  27 10:56 application-1d50e510c33be250476689b997c80411a95686c74d2fb3d8cd61a0b9e084b42b.js
-rwxr-xr-x 1 huginn huginn 178973 nov.  27 10:56 application-217f07c27970aab29070e0ef3564a0242db68b651934ce399e1a559bc7db8500.css
-rwxr-xr-x 1 huginn huginn    613 nov.  25 13:58 diagram-072c739e4bef92087fecac9a4e641837e6a3dcfd05ebc778a7ac4f5404ad911b.js
drwxr-xr-x 2 huginn huginn   4096 nov.  27 11:06 font-awesome
-rwxr-xr-x 1 huginn huginn  12799 nov.  25 13:58 glyphicons-halflings-d99e3fa32c641032f08149914b28c2dc6acf2ec62f70987f2259eabbfa7fc0de.png
-rwxr-xr-x 1 huginn huginn  14079 nov.  25 13:58 glyphicons-halflings-regular-5ff7c239555476e939e86d457bb78424b945b733b2c23791d9807c2357259d43.eot
-rwxr-xr-x 1 huginn huginn  29512 nov.  25 13:58 glyphicons-halflings-regular-cb18b8d11f9698fc8cb3341cb5c882af1103ef8927d34e1602015b5f82eb234f.ttf
-rwxr-xr-x 1 huginn huginn  62927 nov.  25 13:58 glyphicons-halflings-regular-d168d50a88c730b4e6830dc0da2a2b51dae4658a77d9619943c27b8ecfc19d1a.svg
-rwxr-xr-x 1 huginn huginn  23320 nov.  25 13:58 glyphicons-halflings-regular-fc969dc1c6ff531abcf368089dcbaf5775133b0626ff56b52301a059fc0f9e1e.woff
-rwxr-xr-x 1 huginn huginn   8777 nov.  25 13:58 glyphicons-halflings-white-f0e0d95a9c8abcdfabf46348e2d4285829bb0491f5f6af0e05af52bffb6324c4.png
-rwxr-xr-x 1 huginn huginn 167580 nov.  25 13:58 graphing-9045718d23dd30b8e68eb57a076d3772e82da3147c697f2e59a92ea7723ea188.js
drwxr-xr-x 2 huginn huginn   4096 nov.  27 11:06 json-editor
-rwxr-xr-x 1 huginn huginn    356 nov.  25 13:58 map_marker-ef508669b3c04b7afea8043caba6ac252b05752b8c2e01eb1bca1dd483db7aef.js
-rwxr-xr-x 1 huginn huginn  83039 nov.  25 13:58 odin-4aea0258f53748e9cc20b6ddd655824d8d1b26901015d43ad97c6d166bf88227.jpg
-rwxr-xr-x 1 huginn huginn    613 nov.  27 10:56 select2-d6b5d8d83dbc18fb8d77c8761d331cd9e5123c9684950bab0406e98a24ac5ae8.png
-rwxr-xr-x 1 huginn huginn   1849 nov.  27 10:56 select2-spinner-f6ecff617ec2ba7f559e6f535cad9b70a3f91120737535dab4d4548a6c83576c.gif
-rwxr-xr-x 1 huginn huginn    845 nov.  27 10:56 select2x2-6fe28d687dc0ed4d96016238c608ba1e7198c9c9accfa0b360b78018b9fb9bc2.png
-rwxr-xr-x 1 huginn huginn   8685 nov.  25 13:58 spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6

**Comment by dsander** [comment] 2015-12-01 16:32
I am a bit lost, what is the current problem you are experiencing? The easiest way would probably be to  redo/check the setups of the [guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#6-huginn) starting with 6.

If that does not help, try to load huginn in your browser and post the last few entries of every log file listed in the troubleshooting section.

**Comment by cantino** [comment] 2016-02-14 22:48
Closing since we haven't heard back.  Hope it's working for you!

**Closed by cantino** 2016-02-14 22:48 UTC
