### ISSUE TITLE
Events from WebsiteAgent which involve decimal fractions lose precision.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1779] opened 2016-11-04 23:32 UTC
I'm using the WebsiteAgent to pull some market data from an API server which returns data that looks like this:
`{
  "result": "success",
  "marker": "day|20161101000000",
  "count": 1,
  "rows": [
    {
      "avg": 0.005025,
      "max": 10.112625,
      "min": 0.00001,
      "total": 4893.390453,
      "tx_count": 973734,
      "date": "2016-11-04T00:00:00Z"
    }
  ]
}`

I'm using the following JSONpath to extract just the value of "avg": `$.rows.[0].avg`

However, when I trigger a dry run of this agent, it returns events that look like this:

`[ { "fee": 1.0e-05 } ]`

Thinking that I might be doing something wrong, I ran a couple of experiments with some of the [money filters](https://help.shopify.com/themes/liquid/filters/money-filters) implemented by Shopify in their core documentation but that doesn't seem to help any.  I've also examined some events emitted by a few dozen other instances of WebsiteAgent (current relative currency costs) and they all appear as they should (0.00659361, 63.17470586, 43539.46265175, and so forth).

I'm not sure if I'm doing something wrong or what.  Could this be a bug, or is something missing in the documentation someplace, some flag that I'm missing?

**Comment by knu** [comment] 2016-11-05 01:36
If `0.005025` turned to `1.0e-05` that would definitely be a bug, but if `0.00001` did, that would be perfectly fine because there was no precision lost and JSON includes exponents in the specification.  You can safely post it as part of a JSON and the receiver will parse it correctly.  However, if you want to use it a different way like passing it via query string, then you need to format it properly on your own using Liquid because exponents might not be supported by the receiver.

**Comment by virtadpt** [comment] 2016-11-06 22:35
0.005025 does turn into 1.0e-5.

**Comment by knu** [comment] 2016-11-07 07:45
I have no idea how that could happen.  Maybe a hardware problem.  Is there a reproduction?

**Comment by virtadpt** [comment] 2016-11-08 04:28
Raw data: http://pastebin.com/xfSvY2rH

My website agent: http://pastebin.com/VipR9PSV

Result from my WebsiteAgent:
```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://data.ripple.com/v2/network/fees
[00:00:00] INFO -- : Extracting json at $.rows.[0].avg: [1.0e-05]
[00:00:00] INFO -- : Dry Run finished
```

Actual event emitted by the agent during normal operation:
```
Extracting json at $.rows.[0].avg: [1.0e-05]
```

**Comment by cantino** [comment] 2016-11-09 01:22
That says that `avg` is `0.00001`, which is the same as `1.0e-05` with no loss of precision, right?

**Comment by knu** [comment] 2016-11-09 06:40
I think so too.  But by the way, I found Liquid did not have any filter to format a floating point number.  Should we add one?

cf. https://github.com/Shopify/liquid/issues/567

**Comment by dsander** [comment] 2016-11-09 15:59
Liquid has some money related filters https://help.shopify.com/themes/liquid/filters/money-filters but they are probably too specific for most cases. Having a generic number formatted sounds like a good idea, maybe it could be a wrapper around [number_to_human](http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_human)?

**Comment by virtadpt** [comment] 2016-11-11 01:56
@cantino It is not.  The actual value of avg is 0.005025.

@knu It does not have one by default - I spent a couple of hours playing around with existing Liquid filters to see if I could use one or two to do what I needed, and that does not seem to be the case.

@dsander I tried the money-related filters - no dice.

**Comment by knu** [comment] 2016-11-11 02:42
I see no occurence of 0.005025 in the pasted JSON data.

I created an EventFormattingAgent with options:
```json
{
  "instructions": {
    "message": "{{rows[0].avg | as_object}}"
  },
  "mode": "clean"
}
```
and fed the following event to it:
```json
{
  "result": "success",
  "marker": "day|20161101000000",
  "count": 1,
  "rows": [
    {
      "avg": 0.005025,
      "max": 10.112625,
      "min": 0.00001,
      "total": 4893.390453,
      "tx_count": 973734,
      "date": "2016-11-04T00:00:00Z"
    }
  ]
}
```
and the result was this:
```json
{
  "message": 0.005025
}
```
I see no problem at all.

**Comment by knu** [comment] 2016-11-11 02:43
If you omit `| as_object` then the value is `"0.005025"`.

**Comment by knu** [comment] 2016-11-11 02:48
So, we definitely need a repro.  We cannot investigate any further without one.

**Comment by virtadpt** [comment] 2016-11-13 21:09
Going back through the agent network logs, I don't see any harmful effects (though that particular information source has been flat for a couple of days now).  I'll keep an eye on it and comment if anything weird happens.

**Comment by dsander** [comment] 2017-01-30 11:35
@virtadpt Can we close this issue?

**Comment by dsander** [comment] 2017-03-10 15:51
I am closing this issue. Please feel free to reopen if you need further assistance!

**Closed by dsander** 2017-03-10 15:51 UTC
