### ISSUE TITLE
RSS Agent Adding Extra Characters to Google Alerts RSS URLs

### ISSUE THREAD

**Issue by marycanady** [cantino/huginn#889] opened 2015-07-06 22:58 UTC
RSSAgent is adding "amp;" characters at the end of ampersands in URLs it is outputting, how do I prevent or remove? This happens whether or not I use the "clean:true" option. I know Google Alert URLs are long and complex, but I don't know any alternative. Thanks in advance!

Original:
https://www.google.com/url?rct=j&sa=t&url=http://www.vocalrepublic.com/superbug-threat-prompts-west-to-revisit-soviet-era-virus-therapy/15605/&ct=ga&cd=CAIyGjhiMjMxNTkwMzBiNmY1OGU6Y29tOmVuOlVT&usg=AFQjCNFRgagE8CRhJY-oQqfNzxfRAclTeg

RSS Agent Output:
https://www.google.com/url?rct=j&amp;sa=t&amp;url=http://www.vocalrepublic.com/superbug-threat-prompts-west-to-revisit-soviet-era-virus-therapy/15605/&amp;ct=ga&amp;cd=CAIyGjhiMjMxNTkwMzBiNmY1OGU6Y29tOmVuOlVT&amp;usg=AFQjCNFRgagE8CRhJY-oQqfNzxfRAclTeg

**Comment by cantino** [comment] 2015-07-07 02:29
Hey @marycanady, welcome!  Could you show us an example of the Agent configuration that you're using?

**Comment by marycanady** [comment] 2015-07-07 16:06
Thanks so much! Here's the code for RSS Agent. I tried it with and without  "clean": "true" and "disable_url_encoding": "false", and got same results.

{
  "expected_update_period_in_days": "1",
  "clean": "true",
  "url": [
    "https://www.google.com/alerts/feeds/03898956544915458721/17285894713843133113",
    "https://www.google.com/alerts/feeds/03898956544915458721/15913629364926333310",
    "https://www.google.com/alerts/feeds/03898956544915458721/12406979761446534656",
    "https://www.google.com/alerts/feeds/03898956544915458721/8306083851047590634",
    "https://www.google.com/alerts/feeds/03898956544915458721/17175862336702033475",
    "https://www.google.com/alerts/feeds/03898956544915458721/8285209545463460519",
    "https://www.google.com/alerts/feeds/03898956544915458721/6888572221077269259",
    "https://www.google.com/alerts/feeds/03898956544915458721/9995740505253473213",
    "https://www.google.com/alerts/feeds/03898956544915458721/12380540797622417845",
    "https://www.google.com/alerts/feeds/03898956544915458721/4730131601346014722",
    "https://www.google.com/alerts/feeds/03898956544915458721/12430236899926813936",
    "https://www.google.com/alerts/feeds/03898956544915458721/12430236899926812986",
    "https://www.google.com/alerts/feeds/03898956544915458721/9287717967257008409",
    "https://www.google.com/alerts/feeds/03898956544915458721/2379002074155166283",
    "https://www.google.com/alerts/feeds/03898956544915458721/12825266440187028785",
    "https://www.google.com/alerts/feeds/03898956544915458721/16166407750158266610",
    "https://www.google.com/alerts/feeds/03898956544915458721/12718887008787068431",
    "https://www.google.com/alerts/feeds/03898956544915458721/14261209551583029212"
  ],
  "disable_url_encoding": "false"
}

**Comment by virtadpt** [comment] 2015-07-07 19:23
Does this happen with non-Google RSS feeds?

**Comment by cantino** [comment] 2015-07-08 05:12
Hey @marycanady, I'll try setting this up locally and see if I can reproduce.  I'm pretty swamped for the next two days, though, so it may be later in the week or early next week.  If someone else wants to try and debug / fix, go for it! :)

**Comment by knu** [comment] 2015-07-08 06:39
Apparently FeedNormalizer is doing something wrong.

**Comment by knu** [comment] 2015-07-08 07:12
When parsing one of these feeds, FeedNormalizer somehow falls back from the rss parser to the simple-rss parser, and the SimpleRSS generates the wrong URLs.

```ruby
require 'simple-rss'
require 'open-uri'

rss = SimpleRSS.parse open('https://www.google.com/alerts/feeds/03898956544915458721/17285894713843\
133113')

puts rss.items.first.link
#=> https://www.google.com/url?rct=j&amp;sa=t&amp;url=http://www.dakotafinancialnews.com/intrexon-corp-lifted-to-buy-at-zacks-xon/243174/&amp;ct=ga&amp;cd=CAIyGmUxMDlkOTA3MDE0YzQ2ZjY6Y29tOmVuOlVT&amp;usg=AFQjCNH61DNiDuZW20aTxuFzFfNKrlWpVg
```

So, one problem is RSS::Parser failing to parse the feed and another is SimpleRSS not handling XML attributes properly.

**Comment by knu** [comment] 2015-07-08 07:20
This is the current status, and I'm going out for a meal...

**Comment by marycanady** [comment] 2015-07-11 19:27
Thanks! Any updates? It will likely be a significant problem for huginn as so many people use Google Alerts.

**Comment by cantino** [comment] 2015-07-11 23:25
I will try to dig into it this week.

**Comment by knu** [comment] 2015-07-12 04:09
The first problem was due to feed-normalizer not expecting an Atom feed from RSS::Parser.parse(): https://github.com/aasmith/feed-normalizer/blob/master/lib/parsers/rss.rb#L37 (RSS::RDF has channel() while RSS::Atom::Feed does not)

The second "problem" turned out to be a 'feature" of simple-rss, not really dealing with XML at all: https://github.com/cardmagic/simple-rss#usage

**Comment by knu** [comment] 2015-07-12 04:15
So, it would be the best to enhance feed-normalizer to support Atom, but in the meantime we'd have to monkey-patch it.

**Comment by cantino** [comment] 2015-07-13 22:20
Given https://github.com/aasmith/feed-normalizer/issues/4, I doubt feed-normalizer is being maintained.  @knu, does updating it interest you?  If not, I'll take a crack at it.

**Comment by knu** [comment] 2015-07-14 04:00
We could probably use RSS::Parser directly, calling feed-normalizer's HTML cleaner as necessary.

**Comment by cantino** [comment] 2015-07-14 04:05
That might be simpler, if it gives us more control, as I imagine Huginn's RSS parsing needs will only increase with time.

**Comment by marycanady** [comment] 2015-07-14 15:44
Thanks guys, I know you're still working on it, but I'd be happy to contribute somewhere for your time, let me know where!

**Comment by knu** [comment] 2015-07-15 03:13
It's not ideal, but I guess adding a Liquid filter `unescape` wouldn't hurt and mitigate the issue by allowing you to create an EventFormattingAgent to fix the messed up escaped URLs.

**Comment by cantino** [comment] 2015-07-15 21:21
@marycanady, would an `unescape` filter solve this?

**Comment by marycanady** [comment] 2015-07-16 17:36
Hi--thanks! I'm a n00b both on Huginn and Git, has this been created, and if so how do I use it? I'm also using Huginn on Heroku, and from what I remember, they don't have the latest snapshot of Huginn (and I'm not yet savvy enough to add new code) so I don't know if I can use it yet. Will look into it soon and let you know. Have you been able to test?

**Comment by cantino** [comment] 2015-07-16 22:06
@marycanady, it has not been merged into Huginn's master branch yet.  When it is, you'll be able to update your local checkout of Huginn, then push the update to Heroku.  This would be something like `git fetch origin`, then `git merge origin/master`, then `git push heroku master`.

**Comment by marycanady** [comment] 2015-07-26 14:31
Thanks--sorry I have very limited time to work on this right now. Can you please tell me when the change has been merged with the master? Can you also please point me to some instructions on how to use the filter?

**Comment by cantino** [comment] 2015-07-26 21:54
@marycanady, @knu's filter has been merged into master.  It's a normal Liquid filter, as is documented in our wiki.  I think @knu's intention was for you to make an EventFormattingAgent that receives your events, runs the `unescape` filter on the URL parts, and re-emits them.

**Comment by marycanady** [comment] 2015-08-08 15:51
Thanks, I'm finally having time for this now. Somehow I had gotten Huginn working on Heroku without using the command line, and I can't remember how. Do you know if this is possible, and if so, would it be running the most recent version of Huginn?

**Comment by cantino** [comment] 2015-08-08 19:37
Yes, if you're pulling from the current git repo, it should be up to date.

**Comment by marycanady** [comment] 2015-08-09 14:33
Thanks, it's working, the Google Alerts URLs are valid. Here's the code for the Formatting Agent, you can close this item. I would suggest adding that no arguments are needed for the unescape filter in the wiki, as I was unclear on this fact.

{
  "instructions": {
    "title": "Blogs: {{title}}",
    "url": "{{url | unescape }}"
  },
  "matchers": [],
  "mode": "merge"
}

**Comment by cantino** [comment] 2015-08-11 02:02
Glad it's working! Would you mind updating the wiki?

**Comment by cantino** [comment] 2015-08-23 21:47
@marycanady, did my JavaScript Agent work?  If so, would you mind updating the wiki with your successes, and maybe blogging about it? :)

**Closed by cantino** 2015-08-23 21:47 UTC

**Comment by mcanady** [comment] 2015-08-24 16:45
Hi--forgive me, but where would I have gotten the JavaScript Agent?

**Comment by cantino** [comment] 2015-08-24 18:23
I emailed you a week or so ago.  Just replied to it again.

**Comment by knu** [comment] 2018-11-23 13:13
I recently checked out feeds generated by Google Alerts and found out they are Atom documents with `<title type="html"/>` elements.  So, RssAgent should be made aware of that and convert marked-up title contents to plain texts as necessary.

I think that would be the job of the underlying feed parser which currently is Feedjira, so I'm looking to making a PR for it.  We've already been patching Feejira quite heavily, but this would be relatively easy to factor out and feed back.

**Comment by knu** [comment] 2019-07-10 12:32
Finally, here's the work in progress!
https://github.com/feedjira/feedjira/pull/423

**Comment by knu** [comment] 2019-07-10 13:07
And this: https://github.com/feedjira/feedjira/pull/424

**Comment by mcanady** [comment] 2019-07-10 13:52
Thanks! I reread the thread and can't remember how I solved the problem...but the work is appreciated!
