### ISSUE TITLE
docker : can't start a stopped huginn container (pid file issue)

### ISSUE THREAD

**Issue by mhow2** [cantino/huginn#896] opened 2015-07-10 08:07 UTC
running : 

    docker run  -d -it -p 5000:5000 cantino/huginn

waiting for the services to start then stopping the container

    docker stop <id>
    docker start <id>

then start again and you'll get:

    08:01:52 web.1  | A server is already running. Check /app/tmp/pids/server.pid.

NB: using ```docker stop --time=30 <id>``` doesn't help for any reason, I have the feeling the timeout value is not applied and stays 10s

**Comment by cantino** [comment] 2015-07-10 15:11
@icblenke

**Comment by ianblenke** [comment] 2015-07-11 16:54
While I can't reproduce the problem, PR #901 is a guard against this occurrence.

**Comment by mhow2** [comment] 2015-07-21 09:07
Hi @ianblenke  and thank you. I've pulled the cantino/huginn image this morning and can't reproduce the issue anymore. This is strange you haven't been able to reproduce because at the time I've tested this issue, I got reproducing 100% :/ Anyway. It seems fixed.

**Comment by ianblenke** [comment] 2015-08-28 15:31
This problem appears fixed by the merge of #901

**Closed by ianblenke** 2015-08-28 15:31 UTC
