### ISSUE TITLE
Docker mysql linking question

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#887] opened 2015-07-06 20:13 UTC
@mhow2, I saw your comment on the [Huginn Docker image](https://registry.hub.docker.com/u/cantino/huginn/):

```
The usage section explaining how to link to another mysql container doesn't work on my system.

The client container cannot connect to mysql server's container. I'm not sure the ports are exposed the right way ?
```

@icblenke may be able to offer some help.  He also wrote this useful summary: https://github.com/cantino/huginn/pull/872#issuecomment-118552328

**Comment by mhow2** [comment] 2015-07-07 07:01
Thanks @cantino.
Next time I'll do an issue report instead.
About icblenke's comment, I think i'll need to re-read it several times because there is a lot of info in there. As now my goal is to obtain the most 'easy-to-maintain' , 'easy-to-deploy' huginn installation, in a production env. On a single VM :) While I don't need zero-downtime at all.

**Comment by mhow2** [comment] 2015-07-10 10:43
@cantino, @icblenke I think we have an issue somewhere in mysql server configuration that prevents the application container to connect to the database container.

```
docker run --rm --name newcentury_mysql -p 3306 \
    -e HUGINN_MYSQL_DATABASE=huginn \
    -e HUGINN_MYSQL_USER=huginn \
    -e HUGINN_MYSQL_PASSWORD=somethingsecret \
    -e HUGINN_MYSQL_ROOT_PASSWORD=somethingevenmoresecret \
    cantino/huginn
```
- the ```bind-address``` in my.cnf is set to 127.0.0.1 so the other container cannot connect.
- changing the setting above is not enough : here is what I get then:
    Mysql2::Error: Host '172.17.0.7' is not allowed to connect to this MySQL server

So I suspect the huginn user to be allowed to connect *only* from 'localhost'.

I guess the huginn docker deployment need a review. I can test when it's done if you'd like to.

**Comment by ianblenke** [comment] 2015-07-11 03:03
A quick fix for this would be to run both containers with "--net=host" so that localhost would be the same for both containers, but that's really a hack.

I haven't tried reproducing this yet, but I have no doubt you are correct. I'll see if I can generate a PR to address this shortcoming in the near future.

**Comment by ianblenke** [comment] 2015-07-12 04:06
PR #905 should address this. You will want to merge PR #903 as well for the PORT fix.

**Comment by ianblenke** [comment] 2015-08-28 15:28
Issue #887 is now fixed, as PR #905 has been merged.

The only remaining question here is whether the mysql container is actually binding to localhost.

**Comment by cantino** [comment] 2016-02-14 22:44
@dsander, think we can close this?

**Comment by dsander** [comment] 2016-02-14 22:46
Yes we have [documentation](https://github.com/cantino/huginn/tree/master/docker/single-process#usage) for [both](https://github.com/cantino/huginn/tree/master/docker/multi-process#usage) docker images, as well as example docker compose configurations.

**Closed by dsander** 2016-02-14 22:46 UTC
