### ISSUE TITLE
huginn memory leak with no agents running

### ISSUE THREAD

**Issue by jn11** [cantino/huginn#1114] opened 2015-10-27 22:21 UTC
I'm running the latest version of huginn in production environment, fresh install with no agents configured and the memory used is growing indefinitely. Looks like there is a memory leak somewhere. Can someone confirm this issue?

**Comment by cantino** [comment] 2015-10-28 02:01
@dsander and I, among others, have been seeing this as well.  We haven't been able to figure out the cause yet.

**Comment by cantino** [comment] 2015-10-28 02:51
See #978

**Comment by dsander** [comment] 2015-10-28 17:50
@jn11 Did you delete the seeded default Agents or are those still running?

**Comment by jn11** [comment] 2015-10-28 23:08
@dsander I just install huginn and no agents appear, not sure which ones you mean.

**Comment by dsander** [comment] 2015-10-28 23:13
There are a [few agents](https://github.com/cantino/huginn/blob/master/db/seeds.rb#L15-L85) that are created when you first [seed the database](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#initialize-database) to create the admin user. Did you create your user without seeding?

If your database does not contain any agents at all it is a great hint on how to debug the memory leak.

**Comment by jn11** [comment] 2015-10-29 08:56
I created the user directly from the web interface sign-up form (getting
the invitation code from the env variable), so I guess the database should
not contain any agent.

**Comment by cantino** [comment] 2015-10-30 06:12
If you log in as the user and visit /agents, do you see anything in the list?

**Comment by jn11** [comment] 2015-10-30 10:27
no, in the agent list, nothing appears

**Comment by cantino** [comment] 2015-10-31 04:08
This is useful info, thank you.

**Comment by jn11** [comment] 2016-02-23 09:40
I didn't test it again with no agents.

**Comment by cantino** [comment] 2017-01-23 23:17
I'm going to close this issue. Please reopen if you'd like to discuss further.

**Closed by cantino** 2017-01-23 23:17 UTC
