### ISSUE TITLE
Connection timeout error after resume

### ISSUE THREAD

**Issue by peterseverin** [cantino/huginn#1299] opened 2016-02-16 05:39 UTC
I run Huginn in a docker container on my PC which a put to sleep at night. After a resume, things seem to work, events are collected and the web interface works. However I have persistent connection timeout errors in the console that just won't go away. Sometimies it's in huginn_scheduler.rb and sometimes in agent_runner.rb. The only solution is to restart the container. See an example stack trace below.
 
`05:35:18 jobs.1 |   44563300     ActiveRecord::ConnectionTimeoutError
foreman stdout | 05:35:18 jobs.1 |   44563300     could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
05:35:18 jobs.1 |   44563300       /usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
05:35:18 jobs.1 |   44563300       /usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
05:35:18 jobs.1 |   44563300       /usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_handling.rb:87:in `connection'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:48:in `connection'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:980:in `create_binds'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:954:in `build_where'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:584:in `where!'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:574:in `where'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
05:35:18 jobs.1 |   44563300       /app/app/models/agent.rb:74:in `block in <class:Agent>'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:155:in `call'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:155:in `block (2 levels) in scope'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:302:in `scoping'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:155:in `block in scope'
05:35:18 jobs.1 |   44563300       /app/lib/huginn_scheduler.rb:84:in `schedule_scheduler_agents'
05:35:18 jobs.1 |   44563300       /app/lib/huginn_scheduler.rb:135:in `block in setup'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `call'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `do_call'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in `call'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
foreman stdout | 05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `loop'
05:35:18 jobs.1 |   44563300       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
`

**Comment by dsander** [comment] 2016-02-16 09:48
Hi @peterseverin,

interesting that the application server survived the resume. But I am afraid we can not support sleep/resume, huginn is designed to run 24/7, if you need to turn off the computer huginn is running on I recommend doing a clean stop and restart of the container(s).

**Comment by peterseverin** [comment] 2016-02-16 10:05
Sure, I am not looking into specific support for sleep/resume. I just thought that this error indicates a more general problem that could appear in other situations too.

**Comment by cantino** [comment] 2016-02-19 05:41
Thanks for letting us know.

I've never seen it before, so I think it's pretty safe to assume that it's due to the sleep / resume.

I'm going to close the issue, but if you or someone else sees it again in a different context, please re-open!

**Closed by cantino** 2016-02-19 05:41 UTC

**Comment by sadk** [comment] 2016-11-07 02:12
The problem is back。I use the mac computer and docker。

**Comment by cantino** [comment] 2016-11-20 14:56
Hey @sadk, what is your connection pool size? We just increased the default to 20 (from 10), which might help.
