### ISSUE TITLE
Polyglot agent support

### ISSUE THREAD

**Issue by deardooley** [cantino/huginn#1074] opened 2015-10-11 21:26 UTC
It would be immensely valuable to be able to write agents in multiple languages. One approach my team uses us to expose the agent interface as a REST API, then allow users to implement a single class/function that gets injected into a Docker container which is invoked and run like any other agent. This may be a bit of work, but it opens the platform up to contributions and adoption by a significantly larger audience.

**Comment by spaceghost69** [comment] 2015-10-12 02:29
Deardooley, I agree on the need, but I have been contemplating the potential joys of a JRuby implementation... You can mix ruby and java directly in the code (!) and do polyglot through Scala, jpython, inline JavaScript support, access all the java open source libraries to connect to like everything ever, and run in any JVM including docker hosted tomcat or whatnot.

There's a reason so many bpm and eai and soa enterprise integration tools are Java. Cross platform and polyglot and ubiquitous.

Extra bonus is the inline JavaScript support with java 8 and the gorgeous access to react native and other front end goodness with android (Java) and Babel run as a Java process.

**Comment by deardooley** [comment] 2015-10-12 03:29
Sounds like you are pretty much sold. In our experiences, there was just a lot of versioning issues, complex dependencies, resource consumption, and legacy code issues taking a similar approach from prototype to production. Relaxing the runtime opened up the platform to a huge audience without requiring us to scale support staff with the number of users.

Perhaps it's a different use case. Hopefully something to consider in the future. Either way, thanks for the good work.

--
Rion

----- Reply message -----

**Comment by spaceghost69** [comment] 2015-10-12 03:54
Thanks Ripn,

Well, not sold on it but I did let my imagination run wild. I should know better :)

Wow so, that sounds painful sorry jruby didn't fly and thank you for the heads up.  Yeah I was just dreaming actually.

If only it were so easy!  Yeah I saw so many ruby gems I thought unlikely jruby could support it all cleanly. But a guy can dream.

Cool to hear you have it running in big production balls to wall now,  that sounds super cool, you should hire me :)

Sigh, I want to do so very much with Huginn, but there is a gap in usability it's really close but I'm concerned that it is a resource hog I run tomcat normally and am used to optimized Java performance and can't quite wrap my arms around RoR as having good restful separation of concerns for let's say a mobile front end for example, but I'm a Java/JavaScript and front end guy so I'm sure RoR has tricks up the sleeve.  I clearly have more research to do!

**Comment by deardooley** [comment] 2015-10-12 05:14
[We are hiring](https://www.tacc.utexas.edu/about/jobs). Might be worth kicking around a spec document to see what we could do to split front end, back end, and processing with clean apis. If we can sort that out, we can swap the agents out as needed and remove the cpu utilization issues you mentioned.

**Comment by virtadpt** [comment] 2015-10-12 18:02
@spaceghost69 The thing about Huginn is, there are so many ways that you can get data into it for processing with the microservice model.  Huginn parses JSON, XML, and raw text pulled over HTTP(S), and while the webhook functionality takes a little getting used to, it's quite efficient for pushing data into Huginn.  So, you can write microservices (and other bots!) in whatever languages you want and they'll be no less useful.

**Comment by deardooley** [comment] 2015-10-12 18:10
Agreed. I'll take this opportunity to point to issue #1072 ;)

**Comment by spaceghost69** [comment] 2015-10-12 19:26
@virtadpt and @deardooley you guys are great, thanks for the helpful advices!

One idea is to do a basic port to JRuby, then run it side-by-side with Huginn on another port.  Use the same mysql DB so credentials are synchronized.  Then do new Agent development in Polyglot language, while maintaining the idiomatic semantics of Huginn.

Then a roadmap to a full JRuby implementation is straightforward with "backfill" implementation as needed.

**Comment by ssube** [comment] 2015-10-12 23:41
Using an event queue or broker of some sort (even something as simple as redis) could make it much easier to support polyglot agents. Currently, agents are somewhat aware of the events they've seen, so allowing them to run however they like and subscribe to the same central broker would decouple them rather strongly.

**Comment by spaceghost69** [comment] 2015-10-13 02:29
Redis is in interesting approach had not thought of that one.... somehow it needs to integrate with a transactional event bus layer and data state separated from filters and formatters.

**Comment by cantino** [comment] 2015-10-13 02:34
Hey @deardooley, welcome!  We've talked about various polyglot ideas in the past and generally found a way to do what we wanted within the current framework.  (See the ShellCommandAgent for example.)  I'm open to further discussions, though!

@spaceghost69, are you seeing Huginn being a resource hog, or is that hypothetical?

**Comment by spaceghost69** [comment] 2015-10-13 03:18
I'm testing auto scaling and I've had some incidents where the UI was rendered unresponsive.  I'm still trying to determine root causes. Thanks!

**Comment by cantino** [comment] 2016-02-14 22:54
@deardooley, can I close this issue?

**Comment by deardooley** [comment] 2016-02-15 02:02
Yes. I'm actually about to start a round of development related to this issue. I'd I don't diverge off too far from the spirit of the project, I'll issue a pull request.

--
Rion

----- Reply message -----

**Comment by cantino** [comment] 2016-02-15 03:06
Awesome, looking forward!  Feel free to re-open or make a new Issue if needed.

**Closed by cantino** 2016-02-15 03:06 UTC
