### ISSUE TITLE
Run Huginn for free on Heroku

### ISSUE THREAD

**Issue by ppalme** [cantino/huginn#893] opened 2015-07-08 09:43 UTC
I would like to replace yahoo pipes with huginn. In the blog post article "The 13 Best Yahoo Pipes Alternatives You Should Look at Today" Huginn is mentioned as the best alternative. 
I followed your post Run Huginn for free on Heroku. It seems I am missing some steps.

I use a 64-Bit PC with Windows 8.1.

First I have created an account on Heroku.

Second I have installed the Heroku Toolbelt which will also install Ruby 1.9.3. 

Then I start the command window and I can successfully login to Heroku with heroku login.
(email and password).

The next step from then on  is not clear. It says go to your huginn directory and run bundle.
Is this directory on heroku or local?

I concluded that I will have to do another prestep and install git and then clone huginn. I would go to then to the local folder of huginn and type bundle. 
I receive the following message: bundle is not recognized....

What steps am I missing? Thank you.

**Comment by irfancharania** [comment] 2015-07-08 21:09
I wasn't able to get it going on Windows. I ended up downloading a [Linux VM](http://www.osboxes.org/linux-mint/) for [VMWare Player](https://www.vmware.com/products/player)

You should be able to deploy it to Heroku using the [Deploy to Heroku button](https://github.com/cantino/huginn#deployment) on the main page. Then when you launch your app for the first time, you'll be presented with instructions to follow in the Linux VM.

**Comment by cantino** [comment] 2015-07-09 01:23
Welcome @ppalme!  @irfancharania is correct, I think you'll have a *much* better experience if you use a Linux VM for setting up Huginn.  VirtualBox also works well.

**Comment by wasafiri** [comment] 2015-07-12 02:44
I followed the steps to deploy to Heroku and have Huginn running on Heroku. However Heroku keeps sending me warnings saying that my Huginn dyno is running more than 18 hours a day, which after August 15th will lead to forced recharges. Is there any way to allow Huginn to run -- not continuously, but when needed?

**Comment by irfancharania** [comment] 2015-07-12 05:04
Change the schedule frequency of your agents?

**Comment by dsander** [comment] 2015-07-13 19:35
@wasafiri not at the moment. You can try to [remove our keep alive polling](https://github.com/cantino/huginn/blob/master/deployment/heroku/unicorn.rb#L20-L23) and replace it with a cron script that runs on a external server.

**Comment by cantino** [comment] 2015-07-13 22:39
This is related to https://github.com/cantino/huginn/issues/818.

**Comment by wasafiri** [comment] 2015-07-14 01:42
Well, hopefully talks with Heroku will bring a solution to light. If not, I could get something like a Rasp Pi 2 and run Huginn on it. Would the deployment process be similar to the process for Heroku, and if not, could a tutorial be made for those of us that prefer spending $39 on a Rasp Pi vs $7 a month on Heroku?

**Comment by cantino** [comment] 2015-07-14 04:11
I know that we have some instructions [here](https://github.com/cantino/huginn/wiki/Running-Huginn-on-minimal-systems-with-low-RAM-%26-CPU-e.g.-Raspberry-Pi), but I'm not sure how up-to-date they are.  The other option would be to follow @dsander's in-progress [guide](https://github.com/cantino/huginn/pull/872).

**Comment by Arthaey** [comment] 2015-07-18 16:28
I set up Huginn yesterday and got a warning from Heroku this morning, too. I've turned off the Pingdom check that the Huginn setup instructions suggested; I'll see if that's sufficient, or if I get another nastygram tomorrow morning...

**Comment by cantino** [comment] 2015-07-19 02:23
Unfortunately, if you don't keep the instance awake, periodic Huginn activity won't occur.  You may need to pay for the cheapest monthly Heroku offering or use a different VPS provider.

**Comment by Arthaey** [comment] 2015-07-19 02:40
For my (current) purposes, running only once every 8 hours would be sufficient, and would let Heroku's dynos sleep for a 6-hour block like it wants to, right?

If so, putting a note in the installation or newbie guide would be nice, to let folks know they can either get the full experience by paying a little, or tuning things to run "well enough" for free.

**Comment by cantino** [comment] 2015-07-19 03:13
I suspect that a problem may occur with [rufus-scheduler](https://github.com/jmettraux/rufus-scheduler), which we use for scheduling periodic Agents, in which it will likely not work well if it's stopped and started.

You could try pinging your installation every 4hr with Pingdom, but I think this will appear to Huginn as if, every 4 hours, time starts over and runs until Heroku suspends the instance, then time starts over again from 0 some number of hours later when it receives a Pingdom call, and so on.  If you had your Agent set to run every 5 minutes, this would likely work fine since during those periods of uptime, more than 5 minutes would pass, but if you have it run with a frequency less than Heroku's shutdown period, I suspect that it might never run at all.

Is this what other people have observed?

**Comment by dsander** [comment] 2015-07-19 10:37
@cantino I did not try it, but think it works that way

**Comment by cantino** [comment] 2015-07-22 15:59
Since rufus-scheduler doesn't persist any state, Huginn tasks designed to run less often than once every few days may never run.  The chance that your instance goes a week without a restart is real, but if it crashes, or you deploy to it, any every_7d may never get run.  I'm not sure if SchedulerAgents are any more robust to this, but I'm sure crons for specific days and times will ever run if the instance was down during the window.

We may want to remove Agent#SCHEDULES's every_1d, every_2d, and every_7d.

I've also updated our Heroku docs a little.  [Does this](https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-Heroku/_compare/03a16e4fac31c62f734beb95cc8456a4b8072bf0%5E...03a16e4fac31c62f734beb95cc8456a4b8072bf0) sound accurate?

(Dominik, as an aside, maybe we should use the [locking mechanism](https://github.com/jmettraux/rufus-scheduler#lockfile--mylockfiletxt)?)

**Comment by cantino** [comment] 2015-07-22 16:00
Also, since Heroku is no longer a good free option, maybe we should offer a supported https://www.digitalocean.com/features/one-click-apps/?

**Comment by dsander** [comment] 2015-07-22 20:35
> I've also updated our Heroku docs a little. Does this sound accurate?

Looks correct to me.

> (Dominik, as an aside, maybe we should use the locking mechanism?)

Interesting but would that work with the heroku read-only filesystem?

Having a one-click DO app would be awesome, but I was not able to find any documentation on how you submit an application.

**Comment by cantino** [comment] 2015-07-22 20:54
Hmm, you're right about the file locking issue on Heroku.

Do you think we should remove Agent#SCHEDULES's every_1d, every_2d, and every_7d?

**Comment by dsander** [comment] 2015-07-23 21:30
Mhm I can't really imagine a use case for the `every_7d` option, but 1d or 2d do not seem to far fetched. Do you see any harm in the 7d option? (of course none of the three are an option when running on heroku using the hobby tier)

**Comment by cantino** [comment] 2015-07-24 02:54
Well, if you deploy (update Huginn) within those windows, they never run, right?

**Comment by cantino** [comment] 2015-07-26 22:18
I have Pingdom set to hit my test Heroku instance once an hour and I still received their warning, which is surprising.  I'd expect it to be only running for 12 hours a day, as their awake window is 30 minutes and I'm pinging every 60 minutes.  I wonder if the glitch is in Pingdom, Heroku, or my understanding.

**Comment by mightymt** [comment] 2015-07-27 18:36
@cantino: Yes, I was experiencing the same. One explanation would be, if you have any agents with a check interval of 30 minutes or less. Another reason could be, if anyone/anything else accesses Huginn very frequently. 
On the Heroku pricing page it says that a free dyno "Sleeps after 30 mins of **inactivity**".

Also by the way, the scheduler didn't seem to work properly when I pinged my Huginn instance only once an hour (at the top of the hour):
E.g. when I once manually ran an agent (scheduled for hourly checks) at 10:45 it wouldn't get run by the scheduler any more, probably because the Heroku app would ideally only be active every hour from minute 00 to minute 30. I was able to (kind of) reproduce this the other day. At one point when I logged in I saw that same agent with a "last checked" time of "~4h ago". Then I ran it manually once more and it started running on schedule. 

So here's the cron setup I currently use. This keeps my Huginn instance awake constantly from 7AM probably to 12:30AM, which works fine for me and defeats the issues described above. Also I don't get warning e-mails from Heroku any more.

```
*/15 	7-23 	* 	* 	* 	curl https://<huginn>.herokuapp.com/ >/dev/null 2>&1
```

**Comment by cantino** [comment] 2015-07-29 06:36
Right, I think only Agents with schedules more frequent than every 30 minutes would ever run?

I *thought* that our special Heroku Procfile would only run a web worker, which wouldn't be "active" just because of a background thread running.  I thought "active" on Heroku would mean web requests, but perhaps I'm mistaken.

**Comment by mightymt** [comment] 2015-07-29 17:29
@cantino: Just to clarify, what I wrote in my previous comment were mainly assumptions/conclusions I made based on the behaviour I had seen. I have only been using Huginn and Heroku for about a month now.

I did however consult Heroku's documentation just now. Here's the relevant section where they define what is considered "active" (source https://devcenter.heroku.com/articles/dyno-sleeping):

> An app is active if some part of the app is running. For example, if any of the following are true:
> 
>    - There is a web dyno that is receiving traffic.
>    - There is a worker dyno that is running.
>    - A one-off dyno is running. For example, started via the CLI or the scheduler.

**Comment by cantino** [comment] 2015-07-29 18:26
Our Heroku Procfile should only be a webdyno, which is why I'm a bit
surprised.

**Comment by cantino** [comment] 2015-08-05 03:05
I'm trying this again with a 70 min ping instead of 60.

**Comment by cantino** [comment] 2015-08-15 04:53
70 min has seemed to work.

**Comment by dsander** [comment] 2015-08-15 09:07
Interesting, how did you configure your agents?

**Comment by MartinDesigner** [comment] 2015-08-15 16:25
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by wasafiri** [comment] 2015-08-28 13:02
@cantino Has 70min continued to work for you? I also wonder if one can set it to run only during business hours and 'sleep' overnight. That would work also. Many don't have a need to check RSS feeds at 3am.

**Comment by cantino** [comment] 2015-08-28 15:26
Hey @wasafiri, it has sort of worked.  It seems like most days it's fine, and I occasionally receive a warning from Heroku.  Perhaps they don't always spin it down perfectly reliably, so I walk a line and sometimes am up too long.  This change of their's is a pain.

**Comment by mightymt** [comment] 2015-08-28 16:16
@wasafiri: Regarding running Huginn only during business hours, you could use a cron job like the one [I mentioned above](#issuecomment-125299939) (assuming you have some server or webspace that supports cron). I've been using this cron setup for almost two months now without any issues.

@cantino: I have finally put up the step-by-step guide I wrote after I had finally completed the (rather frustrating) Huginn installation process. It's specifically targeted at Windows users who (like myself) are new to Huginn, Heroku, Ruby etc. Feel free to incorporate any or all of it into the official documentation if you want. Here's the link:

https://gist.github.com/mightymt/b86c577e4c0c268f0dd1

**Comment by cantino** [comment] 2015-08-29 04:15
Thanks @mightymt!

**Comment by cantino** [comment] 2015-09-01 03:43
@dsander, would any of @mightymt's guide be worth pulling into /doc?

**Comment by cantino** [comment] 2016-02-14 22:45
I'm going to close this issue.  Please reopen if you want to discuss further!

**Closed by cantino** 2016-02-14 22:45 UTC
