### ISSUE TITLE
How to limit number of events from Website Agent?

### ISSUE THREAD

**Issue by Jogan** [cantino/huginn#1044] opened 2015-09-28 19:07 UTC
I am working to replace my Yahoo pipes implementation. I am using multiple Website Agents to scrape some RSS feeds and then combining them into a single output with a Data Output Agent which only shows 100 events (cant use RSS Agent because it cannot parse the enclosure tags).  The problem I have is some of these website agents emit 100+ events while others only emit 10 or so events which seems to mess up the data output agent (the data output agent will only have 1 event from the 10 event source and then 99 events from the 100+ event source).  Is there a way to limit the number of events that come out of the website agents so that I could get the most recent 10 events or am I going about this wrong?

**Comment by level20peon** [comment] 2015-09-29 09:10
Pipe them through a DeDuplicationAgent after grabbing them via WebsiteAgent?

**Comment by cantino** [comment] 2015-09-30 06:04
Hey @Jogan, is the issue that you're getting duplicates, or that you're getting a much more frequent data feed from one source than from another?

**Comment by johnnyzen** [comment] 2016-04-03 13:40
Hi there

I think my issue is similar.

In my situation I have 3 website agent sources in the output feed.

Source A = 20 events
Source B = 20 events
Source C = 20 events

Output feed limit = 40 events.

In the output feed, source C is completely missing as Source A and Source B take the events to 40 which is the limit of the output feed.

Is there a way to equally combine all sources into the allocated 40 event output limit so all sources have a equal right to be included in the output feed?

**Comment by cantino** [comment] 2016-04-04 03:58
Could you increase the output feed limit?  Otherwise, would the "Ordering events in the output" section in the DataOutputAgent help?

**Comment by johnnyzen** [comment] 2016-04-17 17:12
Hey Cantino

I am ordering by date. But still having the same problem....I think I know the problem...

The output is being created in this way when say the limit is 40:

Fetch Agent A = 20 events
Fetch Agent B = 20 events
*Limit Reached*
*Order By Date*
Fetch Agent C = Not Done

Where it should be this:

Fetch Agent A = 20 events
Fetch Agent B = 20 events
Fetch Agent C = 20 events
*Order By Date*
*Trim to 40 limit*

Does this make sense?, and if so, am I right ? I had a look at the code, but not found where I should be looking but I guess the way you have implemented is different logic to the one I am suggesting.

**Comment by johnnyzen** [comment] 2016-04-17 17:20
This is the line I think from huginn/app/models/agents/data_output_agent.rb

```source_events = sort_events(received_events.order(id: :desc).limit(events_to_show).to_a)```
from: huginn/app/models/agents/data_output_agent.rb

It seems to be only ordering to the limit of events_to_show, rather than ordering before limiting.

Not sure how to fix though?

**Comment by johnnyzen** [comment] 2016-04-17 17:31
Maybe this:
```
ordered_events = sort_events(received_events.order(id: :desc).to_a)
trimmed_events = ordered_events.limit(events_to_show).to_a)
source_events = trimmed_events.limit(events_to_show).to_a)
```

**Comment by johnnyzen** [comment] 2016-04-17 23:46
Sorry for my lack of understanding of ruby.

Anyhows I have fixed by making this change:

```
ordered_events = sort_events(received_events.order(id: :desc).to_a)
source_events = ordered_events.take(events_to_show)
```

replacing
```
source_events = sort_events(received_events.order(id: :desc).limit(events_to_show).to_a)
```
from huginn/app/models/agents/data_output_agent.rb:172

**Comment by cantino** [comment] 2016-04-19 03:26
I think this is a bug.

**Comment by cantino** [comment] 2016-04-19 03:37
The problem is that `received_events.order(id: :desc).to_a` could be really huge.  @knu, any thought on how to do this with Arel?

**Comment by knu** [comment] 2016-04-19 11:49
Ah, so you want to order events before narrowing them by id.  It'd be too expensive to compute the ordering score for every event record stored in the database every time the feed was accessed, so we'd need to cache the results and minimize the computation cost.  Maybe an agent could hold the {events_to_show} highest scoring events in its "memory" storage and update them every time the agent received new events, clearing memory whenever `events_order` or `events_to_show` got modified.

**Comment by johnnyzen** [comment] 2016-04-19 13:33
Yeah I dont think my code is working well, huginn dies after a period of time. Not sure why :(

**Comment by knu** [comment] 2016-04-19 13:54
I think I have an idea, will come up with a patch for testing shortly.

**Comment by knu** [comment] 2016-04-19 14:33
@cantino What do you think about the change above?

**Comment by knu** [comment] 2016-04-20 10:55
Actually, my original intention for the `events_order` option was to control the order of last n items in final RSS/JSON output, not to determine how last n items are selected, hence the option description `Ordering events in the output`.  For example, an RSS feed or a timeline API normally lists items in reverse chronological order (newer items first) while DataOutputAgent lists items in chronological order by default, and events_order was the way to achieve that.
So, this is no quite a "bug" for me.

But if it is not how most users take it, we should perhaps change how it works or maybe provide separate options (like `events_order` and `output_order`).  I've just filed #1444 which tries to get it right, so please give me your feedback.  Thanks!

**Comment by johnnyzen** [comment] 2016-08-05 14:11
you guys are awesome !!!!!

**Closed** 2016-08-08 05:12 UTC
Labels: bug

**Comment by knu** [comment] 2016-08-08 05:21
@Jogan @johnnyzen I've merged the above PR which changes the semantics of the `events_order` option, which will require you to re-configure your agents after upgrading.
The current option `events_order` will be migrated to `events_list_order`, so if you want to control the order of received events instead of that of events listed in the output, please rename `events_list_order` back to `events_order`.
