### ISSUE TITLE
Set up via Docker (Not Heroku): admin:password account does not exist

### ISSUE THREAD

**Issue by ryan-rowland** [cantino/huginn#1258] opened 2016-02-01 19:21 UTC
I installed via Docker on a new DigitalOcean Droplet (Ubuntu 15.10) using this installation guide for Linux: https://github.com/cantino/huginn/blob/master/doc/docker/install.md

After connecting via browser, trying to log in with admin/password throws an "Invalid login or password" error.

**Comment by dsander** [comment] 2016-02-01 20:21
Hi @ryan-rowland,

how did you start the container? `docker run -it -p 3000:3000 cantino/huginn` should automatically seed the database with the default username and password.

**Comment by ryan-rowland** [comment] 2016-02-01 20:39
Hi @dsander,

This was my entire input for the install process on a fresh Ubuntu 15.10 machine:

```
$ sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
$ sudo apt-get install vim
$ vim /etc/apt/sources.list.d/docker.list
# Added appropriate line for Ubuntu 15.10 and saved
$ sudo apt-get update
$ sudo apt-get purge lxc-docker
$ sudo apt-cache policy docker-engine
$ sudo apt-get update
$ sudo apt-get install linux-image-extra-$(uname -r)
$ sudo apt-get install docker-engine
$ sudo service docker start
$ docker run -it -p 3000:3000 cantino/huginn
```

Attempting to log in with the default admin account returns the error in issue description.

**Comment by dsander** [comment] 2016-02-01 22:19
That is strange, I did the same on a fresh droplet and it worked like expected. Do you get this output when you start the container?
```
foreman stderr | + bundle exec rake db:seed
```

Are we using the same image?

```
EPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
cantino/huginn      latest              14b44f606330        3 days ago          850.2 MB
```

**Comment by ryan-rowland** [comment] 2016-02-02 18:26
I don't seem to be getting an `stderr`. Here's the relevant mysql output:

```
2016-02-01 19:17:49,822 INFO spawned: 'mysqld' with pid 696
2016-02-01 19:17:51,108 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-02-01 19:17:51,110 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=localhost
bootstrap stdout | mysqld: available
bootstrap stdout | mysqld: added process group
bootstrap stdout | Starting mysql server...
mysqld stderr | 160201 19:17:50 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
mysqld stdout | 160201 19:17:50 mysqld_safe Logging to '/var/log/mysql/error.log'.
mysqld stdout | 160201 19:17:50 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
bootstrap stdout | .2016-02-01 19:17:52,324 INFO spawned: 'foreman' with pid 1072
2016-02-01 19:17:52,331 INFO success: foreman entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-02-01 19:17:52,353 INFO exited: bootstrap (exit status 0; expected)
foreman stdout | Migrating to DeviseCreateUsers (20120728210244)
foreman stdout | == 20120728210244 DeviseCreateUsers: migrating ================================ foreman stdout |
foreman stdout | -- create_table(:users) foreman stdout |
foreman stdout |    -> 0.0039s foreman stdout |
foreman stdout | -- add_index(:users, :email, {:unique=>true}) foreman stdout |
foreman stdout |    -> 0.0084s foreman stdout |
-- add_index(:users, :reset_password_token, {:unique=>true})
foreman stdout |    -> 0.0075s
== 20120728210244 DeviseCreateUsers: migrated (0.0240s) =======================

foreman stdout | Migrating to AddAdminToUsers (20120728215449)
foreman stdout | == 20120728215449 AddAdminToUsers: migrating ================================== foreman stdout |
foreman stdout | -- add_column(:users, :admin, :boolean, {:default=>false, :null=>false}) foreman stdout |
foreman stdout |    -> 0.0059s foreman stdout |
foreman stdout | == 20120728215449 AddAdminToUsers: migrated (0.0083s) ========================= foreman stdout |
foreman stdout |
foreman stdout | Migrating to EnableLockableStrategyForDevise (20120919061122)
foreman stdout | == 20120919061122 EnableLockableStrategyForDevise: migrating ================== foreman stdout |
foreman stdout | -- add_column(:users, :failed_attempts, :integer, {:default=>0}) foreman stdout |
foreman stdout |    -> 0.0056s foreman stdout |
-- add_column(:users, :unlock_token, :string)
foreman stdout |    -> 0.0045s
-- add_column(:users, :locked_at, :datetime)
foreman stdout |    -> 0.0048s
-- add_index(:users, :unlock_token, {:unique=>true})
foreman stdout |    -> 0.0078s
== 20120919061122 EnableLockableStrategyForDevise: migrated (0.0240s) =========

foreman stdout | Migrating to AddUsernameToUsers (20120919063304)
foreman stdout | == 20120919063304 AddUsernameToUsers: migrating =============================== foreman stdout |
foreman stdout | -- add_column(:users, :username, :string) foreman stdout |
foreman stdout |    -> 0.0050s
foreman stdout | -- change_column(:users, :username, :string, {:null=>false}) foreman stdout |
foreman stdout |    -> 0.0110s foreman stdout |
foreman stdout | -- add_index(:users, :username, {:unique=>true}) foreman stdout |
foreman stdout |    -> 0.0088s
== 20120919063304 AddUsernameToUsers: migrated (0.0357s) ======================
```

And when I try to log in, this appears in the log:

```
foreman stdout | 19:21:06 web.1  | [f577f2dc-164b-4c83-8857-c00f6059d375]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"A8uDcwMdgFlZ9Y5QQbJQogKxxSxusXOuL6H4vj5zxDgMYRi6Rk8vHYyk7cs5rWr1wA9OELPgSFoH5SZjLNJGJA==", "user"=>{"login"=>"admin", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
```

Where did the image information you posted come from? I performed my installation by starting a Ubuntu 15.10 droplet and running the commands from my prior comment; I don't think I used any huginn-specific images.

**Comment by dsander** [comment] 2016-02-02 20:38
Hmm I [pasted my full log output](http://pastie.org/private/oioqiym7uykmos9rwdg7w), the seeding should happen after all the migrations finished and before foreman outputs the services started.

I am not sure if the variable would be populated by docker without explicitly setting it, but do you have the `DO_NOT_SEED` environment variable set?

**Comment by ryan-rowland** [comment] 2016-02-02 21:26
Ah, I see it now. Here's my full log. It is present at the end of the file.

http://pastie.org/10706148

**Comment by dsander** [comment] 2016-02-02 21:54
That is really confusing me. Can you try the following?

```
# Start the container and run the command in a different shell (replace suspicious_mcnulty with the id or name of the running container)
docker exec -it suspicious_mcnulty /bin/bash

# Inside the container
bundle exec rails c

# Inside the rails console
a = User.first
a.password = 'password'
a.password_confirmation = 'password'
a.save!
```

**Comment by ryan-rowland** [comment] 2016-02-02 22:14
First two steps work fine, I error in the Rails console (Looks like User has no rows? I'm not well versed in RoR):

```
irb(main):004:0> User
=> User(id: integer, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, remember_created_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: string, last_sign_in_ip: string, created_at: datetime, updated_at: datetime, admin: boolean, failed_attempts: integer, unlock_token: string, locked_at: datetime, username: string, invitation_code: string, scenario_count: integer)
irb(main):005:0> User.first
=> nil
irb(main):006:0> a.password = 'password'
NoMethodError: undefined method `password=' for nil:NilClass
```

**Comment by dsander** [comment] 2016-02-02 22:29
That is correct, the user that should have been created by `db:seed` does not exists.

Please try this in the same rails console
```
user = User.find_or_initialize_by(:email => ENV['SEED_EMAIL'] || "admin@example.com")
user.username = ENV['SEED_USERNAME'] || "admin"
user.password = ENV['SEED_PASSWORD'] || "password"
user.password_confirmation = ENV['SEED_PASSWORD'] || "password"
user.invitation_code = User::INVITATION_CODES.first
user.admin = true
user.save!
```

If that did not work please paste the output of `ENV` (also in the rails console)

Hopefully at least this works:
```
user = User.find_or_initialize_by(:email => "admin@example.com")
user.username = "admin"
user.password = "password"
user.password_confirmation = "password"
user.invitation_code = User::INVITATION_CODES.first
user.admin = true
user.save!
```

**Comment by ryan-rowland** [comment] 2016-02-02 23:53
Running Rails in a separate window causes the container to get killed, so I can't test this live although taking those steps in Rails seems to be successful.

Container being killed when Rails starts:
```
23:34:52 web.1  | [2016-02-02 23:34:52] INFO  ruby 2.2.4 (2015-12-16) [x86_64-linux-gnu]
23:34:52 web.1  | [2016-02-02 23:34:52] INFO  WEBrick::HTTPServer#start: pid=1135 port=3000
foreman stdout | 23:34:54 jobs.1 | Starting DelayedJobWorker
foreman stdout | 23:34:54 jobs.1 | 2016-02-02T23:34:54+0000: [Worker(host:70a60de61e99 pid:1138)] Starting job worker
foreman stdout | 23:35:28 jobs.1 | exited with code 137
23:35:28 system | sending SIGTERM to all processes
23:35:28        | Killed
23:35:28 web.1  | terminated by SIGTERM
2016-02-02 23:35:28,205 INFO exited: foreman (exit status 0; expected)
```

But it I can verify it does look like the ENV variables are not being set for some reason:
```
irb(main):001:0> ENV['SEED_USERNAME']
=> nil
irb(main):002:0> ENV['SEED_PASSWORD']
=> nil
irb(main):003:0> ENV['SEED_EMAIL']
=> nil
```

**Comment by egeozcan** [comment] 2016-02-03 10:35
I installed docker in a fresh droplet (Ubuntu 14.04) on digitalocean and when I install huginn, I also have the same problem. I can give you shell access if you want to debug.

**Comment by dsander** [comment] 2016-02-03 11:48
@egeozcan That would be great, here is my public ssh key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyZHgJOwWdOzfY8meCTa5CQXlGwkM7QNfF735pDfCCUIbSVJICFYl9Rl+rn2JD7VNjW0BgKiCnW+YbrgZj8DJDaSKXlLWreaUKhKBY9UU6vYO4MczMMQeEVNl0u4PhTF668dtd9nm3j+U+9nRRdYb7t8bDPM7vlcVXX9myuNpUWOQcuKcB/T9LukG/nM3nIc9Uji7pNhh+nLmFOPFag/1aFv7yqjJ7/0b3nrPD8A4VOOAPYVkZuiwcw6oMmCIeggSkpJf4E5oQSaiYp6bbjNkclUlrXJCdnYtJNUKDybsJnCGYVc/9j4G9S3OPwxifIK5u+msKwrPPdV0Y1hqua2cTw==
```

**Comment by egeozcan** [comment] 2016-02-03 17:47
@dsander it's a 5$ DO droplet @ 188.166.18.38, I created a user with that key for you and gave you root. I'll create a fresh droplet later so break it to your heart's content :+1:

**Comment by dsander** [comment] 2016-02-03 20:07
@egeozcan Thanks, I was not able to login to your droplet, but the 512MB was the hint that I needed. With the smallest droplet I am getting the same results you have. It looks like that all combinations of the docker containers need at least 1GB of RAM to boot and function properly.

**Comment by egeozcan** [comment] 2016-02-03 20:55
@dsander oh, sorry I forgot to tell the username (which was your Github username) -- anyway, now I'll try another, more capable server, let's see how it goes.

**Comment by gdomod** [comment] 2016-02-23 13:31
signup with "try-huginn" and connect to bash with docker exec -it DOCKERNAME /bin/bash

mysql -uroot -ppassword huginn_production
update users set admin=1 where id=1;

#create a admin users

**Comment by dsander** [comment] 2016-02-23 14:00
@gdomod Sorry, I don't follow?

**Comment by gdomod** [comment] 2016-02-23 14:23
@dsander i also create a docker huginn container with do-not-seed.
the problem is there are no admin created. 

my workaround are:
i opend the signup page and register a new account.
after this i connected to docker container and edit the mysql user table and make registred user as an admin user.

**Comment by dsander** [comment] 2016-02-23 19:39
Ah I see, yes that is a good tip.

**Comment by cantino** [comment] 2016-04-13 20:15
I'm going to close this.  Please reopen if you have more questions!

**Closed by cantino** 2016-04-13 20:15 UTC
