### ISSUE TITLE
Help with running multi workers

### ISSUE THREAD

**Issue by bluesea1001** [cantino/huginn#977] opened 2015-08-19 05:33 UTC
Hi all,

I trying to have a lot of agents that run frequently(about 6000 agents per 5 mins for one round).

I was follow https://github.com/cantino/huginn/wiki/Running-Many-Job-Workers install guide

After running multi job workers(three workers), 

I found there are some agents have been done more than twice.

Is there a setting I have not noticed?

BR,
Austin

**Comment by dsander** [comment] 2015-08-19 08:37
Hi @bluesea1001,

I have not tried the instructions in the wiki myself but I think they are missing the `-i` argument to give the additional workers a unique identifier. In my tests [this Procfile](https://github.com/dsander/huginn/blob/97ceff62b3ce3e3d892c35c876a09a64bd77b1dd/Procfile#L42-L50) configuration worked.

**Comment by cantino** [comment] 2015-08-19 16:41
I believe that we will be removing those wiki instructions and replacing
them with @dsander's setup instructions in the repo soon too.

**Comment by bluesea1001** [comment] 2015-08-20 05:48
Hi @dsander @cantino ,

I was using bundle execute rake jobs:work in Procfile then set currency to add works with foreman. It is somehow like write multi lines of delay_jobs and work fine until we set lot of jobs run at the same time.

I'm simulate  the case we receive lot of events and jobs. So I add 2000 PostAgents that will send request to 2000 WebhookAgents each create event and has 2000 TestAgents receive and create new event to check to rundown is correct.

But when the test running, we found there will be some case a event propagate twice, means there will be two delay_jobs records and the agent do receive twice while we expect it should run just once. And we do not sure if there has the chance an delay_jobs will be call twice while we has huge amount agent in db

We wonder if anyone has relate experience or any advice.

Thanks.

**Comment by dsander** [comment] 2015-08-20 18:17
For me the foreman concurrency option was not working at all, did you try the Procfile setup I linked earlier?

**Comment by bluesea1001** [comment] 2015-08-21 00:43
Yes, I have done as you say earlier. 

But,  there are still some agents have been done more than twice.

**Comment by cantino** [comment] 2015-08-21 03:14
You might need to show us an example of an Event propagating twice.  That should only be possible if you're using a non-transactional DB or there is a bug in delayed_job.

**Comment by bluesea1001** [comment] 2015-08-21 06:53
In my TestAgent's receive method , I create event with id of incoming event in payload and run for a while then check the new events, there will be some event has same incoming event id in it's payload. 

I'm using MySQL.

**Comment by dsander** [comment] 2015-08-21 15:13
Can you share the scenario JSON of your test setup?

**Comment by dsander** [comment] 2015-08-21 19:12
I was able to reproduce it using the following script, it create 2000 Post- and WebHookAgents which are triggered by one ManualEventAgent:

```
trigger = User.find(1).agents.create!(type: "Agents::ManualEventAgent", name: "PostTrigger")

2000.times do |i|
  options = {"secret"=>"supersecretstring", "expected_receive_period_in_days"=>1, "payload_path"=>"payload"}
  webhook = User.find(1).agents.create!(type: 'Agents::WebhookAgent', name: "Webhook #{i}", options: options)
  options = {"post_url"=>"http://localhost/users/1/web_requests/#{webhook.id}/supersecretstring", "expected_receive_period_in_days"=>"1", "content_type"=>"form", "method"=>"post", "payload"=>{"payload"=>{"agent"=>"#{i}"}}, "headers"=>{}}
  webhook = User.find(1).agents.new(type: 'Agents::PostAgent', name: "Post #{i}", options: options)
  webhook.sources << trigger
  webhook.save!
end
```
After everything finished I would expect 2001 Events but most of the time get a few duplicates like @bluesea1001 mentioned.

The problem seems to be some of the Jobs can not be deleted:
```
   Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: DELETE FROM `delayed_jobs` WHERE `delayed_jobs`.`id` = 7767
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
```

DJ rescues the exception and re-runs the job, because our code already ran the event is created twice. Seems to be a [known](https://github.com/collectiveidea/delayed_job/issues/658) but rare bug of DelayedJob which happens when you rapidly process a lot of jobs.

Not sure what we can do about it.

**Comment by cantino** [comment] 2015-08-21 19:41
Oh wow, we totally ran into this last week at my day job when we upgraded to Rails 4.

We had deadlocks in DJ until we forked delayed_job_active_record and set it to use the older, less deadlock-y sql scope provided by this PR: https://github.com/collectiveidea/delayed_job_active_record/pull/111

To use it, we added this to our delayed_job initializer:

```ruby
Delayed::Backend::ActiveRecord.configure do |config|
  config.reserve_sql_strategy = :default_sql
end
```

Could you try adding this to the Gemfile and using the above initializer and seeing it it fixes it?

```ruby
gem 'delayed_job_active_record', :git => 'https://github.com/mavenlink/delayed_job_active_record', :branch => 'mavenlink'
```

If it does, I'll fork delayed_job_active_record and merge in that PR so that we're not reliant on Mavenlink's fork.

**Comment by dsander** [comment] 2015-08-21 20:09
Got some strange `invalid multibyte char (US-ASCII)` errors in the debian test VM caused by the umlaut in the [Gemspec](https://github.com/mavenlink/delayed_job_active_record/blob/master/delayed_job_active_record.gemspec#L5), not sure if that was caused by me fiddling with Gemfile and Gemfile.lock on the production setup but we should verify it does not happen normally.

The good new is that seems to have fixes the issue, ran the test 5 times and it always worked. It's noticeably slower but i guess that is not really an issue.

**Comment by cantino** [comment] 2015-08-21 20:52
Thanks for testing it.  I just forked the gem and created `https://github.com/cantino/delayed_job_active_record` with branch `configurable-reserve-sql-strategy`.  Can you point at that and see if the encoding issue is fixed?  If it is, mind making a PR?

**Comment by dsander** [comment] 2015-08-23 15:16
@bluesea1001 Can you update your huginn instance and check if the issue is fixed?

**Comment by bluesea1001** [comment] 2015-08-24 06:25
Yes, We use the configuration and resolve our original problem.

But after using this solution, we can run from 6000 agents to just 3000 agents.

**Comment by cantino** [comment] 2015-08-24 15:36
How many delayed job workers are you running?

**Comment by bluesea1001** [comment] 2015-08-25 01:08
Hi @cantino , It's running three DJ workers.

**Comment by cantino** [comment] 2015-08-25 01:48
3000 agents is a lot.  What are you using it for, if I may ask?

**Comment by bluesea1001** [comment] 2015-08-25 06:27
We want to build lite IFTTT like services.

**Comment by cantino** [comment] 2015-08-25 20:00
It should be possible to get Huginn working with this many Agents, but it will likely take some optimization on your part.  I've personally never pushed it that far.  Running more DJ workers, maybe switching to Postgresql, maybe considering using Resque instead of delayed_job, would all be options.  Is this going to be a paid service?

**Comment by bluesea1001** [comment] 2015-08-26 08:43
Thanks for your suggestion. We will try it out!

It's not paid service for user right now, we will charge money from hardware provider(I think XD).
But for now, it is totally free.

**Comment by cantino** [comment] 2015-08-26 14:53
That's great, I'd love for you to be building on top of Huginn. Any attempt
to productionalize will probably require some development time on your
part, and I hope that you can send contributions back to us! :)

**Comment by cantino** [comment] 2016-02-14 22:49
I'm going to close this issue.  Please reopen if you want to discuss further!

**Closed by cantino** 2016-02-14 22:49 UTC
