### ISSUE TITLE
DataOutputAgent : events_order sorting problem

### ISSUE THREAD

**Issue by yodaime08** [cantino/huginn#1043] opened 2015-09-28 12:12 UTC
In my Website Agent I have this extract : 

"Position": {
      "css": "//*[@id=\"panel-standing-85197\"]/div/table/tbody/tr/td[1]",
      "value": "number(.//text())"
    }

In my events_order I have this : 

"events_order": [
    ["{{Position}}", "number", true]"
  ]

When I make a run, events are ordered like this : 

    "Position": "1",
    "Position": "10"
    "Position": "11"
    ....
    "Position": "8"
    "Position": "9"

Anyone know how to have this sort?

    "Position": "1",
    ...
    "Position": "8"
    "Position": "9"
    "Position": "10"
    "Position": "11"

**Comment by knu** [comment] 2015-09-28 14:15
I think the correct value for sorting it numerically ascending orger would be `"events_order": [ ["{{Position}}", "number"] ]`.

**Comment by knu** [comment] 2015-09-28 14:17
I see an extra `"` at the end of a line.  Did you edit it by hand when posting this?

**Comment by yodaime08** [comment] 2015-09-28 14:20
With this : 

"events_order": [ ["{{Position}}", "number"] ]

same result

**Comment by knu** [comment] 2015-09-28 14:26
Same?  Then no sorting is likely to be performed at all.  It is hard to guess based on partial information.

**Comment by yodaime08** [comment] 2015-09-28 14:31
This is my agent : 

{
  "expected_update_period_in_days": "2",
  "url": "http://www.eurosport.fr/basketball/pro-a/2014-2015/standing.shtml",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "Position": {
      "css": "//*[@id=\"panel-standing-85197\"]/div/table/tbody/tr/td[1]",
      "value": "number(.//text())"
    },
    "Equipe": {
      "css": "//*[@id=\"panel-standing-85197\"]/div/table/tbody/tr/td[2]",
      "value": ".//text()"
    },
    "Joue": {
      "css": "//*[@id=\"panel-standing-85197\"]/div/table/tbody/tr/td[4]",
      "value": ".//text()"
    },
    "Gagne": {
      "css": "//*[@id=\"panel-standing-85197\"]/div/table/tbody/tr/td[5]",
      "value": "number(.//text())"
    },
    "Perdu": {
      "css": "//*[@id=\"panel-standing-85197\"]/div/table/tbody/tr/td[6]",
      "value": ".//text()"
    },
    "Image": {
      "css": ".standing_teamsports_v8 table tr td.team-name img",
      "value": "@data-lazy"
    }
  },
  "events_order": [
    "[\"{{Position}}\", \"number\", true]"
  ]
}

And this is the result : 

[
  {
    "Position": "1",
    "Equipe": "Strasbourg",
    "Joue": "34",
    "Gagne": "30",
    "Perdu": "4",
    "Image": "http://i.eurosport.com/_iss_/sport/Allsports/club/logo/medium/12434.png"
  },
  {
    "Position": "10",
    "Equipe": "Dijon",
    "Joue": "34",
    "Gagne": "17",
    "Perdu": "17",
    "Image": "http://i1.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22439.png"
  },
  {
    "Position": "11",
    "Equipe": "Paris-Levallois",
    "Joue": "34",
    "Gagne": "17",
    "Perdu": "17",
    "Image": "http://i1.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22364.png"
  },
  {
    "Position": "12",
    "Equipe": "Châlons-Reims",
    "Joue": "34",
    "Gagne": "17",
    "Perdu": "17",
    "Image": "http://i1.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22586.png"
  },
  {
    "Position": "13",
    "Equipe": "Pau-Lacq-Orthez",
    "Joue": "34",
    "Gagne": "13",
    "Perdu": "21",
    "Image": "http://i2.eurosport.com/_iss_/sport/Allsports/club/logo/medium/11805.png"
  },
  {
    "Position": "14",
    "Equipe": "Cholet",
    "Joue": "34",
    "Gagne": "13",
    "Perdu": "21",
    "Image": "http://i1.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22410.png"
  },
  {
    "Position": "15",
    "Equipe": "Rouen",
    "Joue": "34",
    "Gagne": "12",
    "Perdu": "22",
    "Image": "http://i.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22467.png"
  },
  {
    "Position": "16",
    "Equipe": "Orléans",
    "Joue": "34",
    "Gagne": "10",
    "Perdu": "24",
    "Image": "http://i.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22428.png"
  },
  {
    "Position": "17",
    "Equipe": "Bourg-en-Bresse",
    "Joue": "34",
    "Gagne": "9",
    "Perdu": "25",
    "Image": "http://i2.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22345.png"
  },
  {
    "Position": "18",
    "Equipe": "Boulogne-sur-Mer",
    "Joue": "34",
    "Gagne": "9",
    "Perdu": "25",
    "Image": "http://i2.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22588.png"
  },
  {
    "Position": "2",
    "Equipe": "Nanterre",
    "Joue": "34",
    "Gagne": "25",
    "Perdu": "9",
    "Image": "http://i.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22361.png"
  },
  {
    "Position": "3",
    "Equipe": "Limoges",
    "Joue": "34",
    "Gagne": "23",
    "Perdu": "11",
    "Image": "http://i2.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22355.png"
  },
  {
    "Position": "4",
    "Equipe": "Le Mans",
    "Joue": "34",
    "Gagne": "19",
    "Perdu": "15",
    "Image": "http://i1.eurosport.com/_iss_/sport/Allsports/club/logo/medium/20535.png"
  },
  {
    "Position": "5",
    "Equipe": "ASVEL Lyon-Villeurbanne",
    "Joue": "34",
    "Gagne": "19",
    "Perdu": "15",
    "Image": "http://i1.eurosport.com/_iss_/sport/Allsports/club/logo/medium/11790.png"
  },
  {
    "Position": "6",
    "Equipe": "Le Havre",
    "Joue": "34",
    "Gagne": "19",
    "Perdu": "15",
    "Image": "http://i2.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22462.png"
  },
  {
    "Position": "7",
    "Equipe": "Nancy",
    "Joue": "34",
    "Gagne": "18",
    "Perdu": "16",
    "Image": "http://i.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22067.png"
  },
  {
    "Position": "8",
    "Equipe": "Elan Chalon",
    "Joue": "34",
    "Gagne": "18",
    "Perdu": "16",
    "Image": "http://i.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22426.png"
  },
  {
    "Position": "9",
    "Equipe": "Gravelines-Dunkerque",
    "Joue": "34",
    "Gagne": "18",
    "Perdu": "16",
    "Image": "http://i2.eurosport.com/_iss_/sport/Allsports/club/logo/medium/22398.png"
  }
]

**Comment by knu** [comment] 2015-09-28 14:37
> "[\"{{Position}}\", \"number\", true]"

I see.  This is a duplicate of #1041.  Input it as a JSON structure, not as a string.

**Comment by knu** [comment] 2015-09-28 14:39
Also, as I wrote above, if you want to sort numbers in ascending order, the third element of the tuple should not be "true".  Change it to "false" or just omit it.

**Comment by yodaime08** [comment] 2015-09-28 14:58
I works !

With this : 

"events_order": [
    [
      "{{Position}}",
      "number",
      false
    ]
  ]

Sort is ok.

Thank you very much knu.

**Comment by knu** [comment] 2015-09-28 14:59
Cool, glad it worked.

**Closed** 2015-09-28 14:58 UTC
