### ISSUE TITLE
Webhook Agent does not properly handle Liquid templating.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1070] opened 2015-10-10 20:57 UTC
Webhook Agent does not correctly substitute {% credential foo %} strings in its configuration.  The Agents' POST URLs are broken and unusable.  For example:
```
{
  "secret": "{% credential foo %}",
  "expected_receive_period_in_days": 365,
  "payload_path": "."
}
```
results in a POST URL of **https://huginn.example.com/users/1/web_requests/31337/%7B%25%20credential%20foo%25%7D**, which is incorrect.

**Comment by cantino** [comment] 2015-10-13 01:39
Interesting.  Clearly that URL is wrong, but if you actually post to `https://huginn.example.com/users/1/web_requests/31337/VALUE_OF_CREDENTIAL_FOO`, does it work?  It looks like we do correctly do `interpolated['secret']`, so I'd expect it to.

**Comment by cantino** [comment] 2016-02-14 22:53
Can I close this @virtadpt?

**Closed** 2016-04-13 20:19 UTC

**Comment by ismail44** [comment] 2016-05-30 12:53
This is also the case when using the PostAgent. LiquidTemplating placeholders are not being replaced with the appropriate options.

**Comment by cantino** [comment] 2016-08-29 19:23
@ismail44 for which options?

**Comment by ismail44** [comment] 2016-08-29 19:24
I honestly don't remember... this was a while ago... sorry.

**Comment by cantino** [comment] 2016-08-29 22:53
No worries!

**Comment by xnaas** [comment] 2020-03-31 15:34
Sorry to bump an incredibly old thread. You never got a reply from @virtadpt, but I can confirm that even though the URL is being displayed incorrectly, sending a POST request to the WebhookAgent with the secret key does indeed work. Anyway to get the aesthetic error resolved? 😃

**Comment by virtadpt** [comment] 2020-03-31 17:15
Crap, I completely forgot about this.  I need to test it later today.
